import { Request, Response } from 'express';
import axios from 'axios';
import {
  CropRecommendationInput,
  REQUIRED_CROP_FIELDS
} from '../models/cropRecommendationModel';
import { predictCropWithPython } from '../utils/pythonCropPredictor';

type FastApiPredictResponse = {
  best_crop: string;
  confidence: number; // 0..100
  alternatives: Array<{ crop: string; confidence: number }>; // 0..100
  confidence_level?: string;
  estimated_revenue_rs?: number;
  estimated_profit_rs?: number;
};

const toNumericInput = (body: Record<string, unknown>): CropRecommendationInput => {
  const input = {} as CropRecommendationInput;

  for (const field of REQUIRED_CROP_FIELDS) {
    const rawValue = body[field];
    const numericValue = typeof rawValue === 'number' ? rawValue : Number(rawValue);

    if (!Number.isFinite(numericValue)) {
      throw new Error(`Invalid value for ${field}`);
    }

    input[field] = numericValue;
  }

  return input;
};

export const postCropRecommendation = async (req: Request, res: Response) => {
  const startedAt = Date.now();

  try {
    const input = toNumericInput(req.body as Record<string, unknown>);
    console.log('[crop-recommend] request received', input);

    const fastApiUrl = String(process.env.CROP_RECO_API_URL || '').trim().replace(/\/+$/, '');
    if (fastApiUrl) {
      try {
        const payloadForFastApi = {
          N: input.nitrogen,
          P: input.phosphorus,
          K: input.potassium,
          temperature: input.temperature,
          humidity: input.humidity,
          ph: input.ph,
          rainfall: input.rainfall,
          budget: Number(req.body?.budget) > 0 ? Number(req.body.budget) : 0,
        };

        const fastApiResponse = await axios.post<FastApiPredictResponse>(
          `${fastApiUrl}/predict`,
          payloadForFastApi,
          {
            timeout: 12000,
            headers: { 'Content-Type': 'application/json' },
          }
        );

        const fast = fastApiResponse.data;
        const normalizedConfidence = Math.max(0, Math.min(1, Number(fast.confidence || 0) / 100));
        const alternatives = (fast.alternatives || []).map((item) => ({
          crop: item.crop,
          confidence: Math.max(0, Math.min(1, Number(item.confidence || 0) / 100)),
        }));

        const top_predictions = [
          { crop: fast.best_crop, confidence: normalizedConfidence },
          ...alternatives,
        ].slice(0, 3);

        res.status(200).json({
          recommended_crop: fast.best_crop,
          confidence: normalizedConfidence,
          top_predictions,
          alternatives,
          explanation: fast.confidence_level
            ? `Confidence Level: ${fast.confidence_level}`
            : 'Prediction generated by FastAPI crop model.',
          estimated_revenue_rs: fast.estimated_revenue_rs,
          estimated_profit_rs: fast.estimated_profit_rs,
          source: 'fastapi',
        });
        return;
      } catch (fastApiError) {
        console.warn('[crop-recommend] FastAPI call failed, falling back to local predictor', {
          message: (fastApiError as Error).message,
        });
      }
    }

    const prediction = await predictCropWithPython(input);
    console.log('[crop-recommend] prediction success', {
      recommendedCrop: prediction.recommended_crop,
      confidence: prediction.confidence,
      latencyMs: Date.now() - startedAt,
    });

    res.status(200).json({
      ...prediction,
      source: 'python-local',
    });
  } catch (error) {
    const message = (error as Error).message || 'Unable to generate crop recommendation';
    console.error('[crop-recommend] prediction failed', {
      message,
      latencyMs: Date.now() - startedAt,
      body: req.body,
    });

    res.status(400).json({
      message,
      hint: 'Ensure backend model is trained and request includes all numeric crop parameters.'
    });
  }
};
