import Scheme from '../models/Scheme';

const schemeSeeds = [
  {
    name: 'PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)',
    state: 'All India',
    category: 'Income Support',
    description: 'Provides eligible farmer families with direct income support of Rs. 6,000 per year in three equal installments.',
    eligibility: 'Land-holding farmer families with valid Aadhaar and bank account details. Institutional landholders are excluded.',
    documents: ['Aadhaar Card', 'Land Records', 'Bank Passbook', 'Mobile Number'],
    benefits: 'Direct financial support of Rs. 6,000 annually credited to beneficiary bank account.',
    application_link: 'https://pmkisan.gov.in/',
  },
  {
    name: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
    state: 'All India',
    category: 'Crop Insurance',
    description: 'Affordable crop insurance scheme protecting farmers against crop loss due to natural calamities, pests, and diseases.',
    eligibility: 'All farmers including sharecroppers and tenant farmers growing notified crops in notified areas.',
    documents: ['Aadhaar Card', 'Bank Account Details', 'Land Records or Tenancy Proof', 'Sowing Certificate'],
    benefits: 'Low premium rates with claim support for crop loss and post-harvest losses.',
    application_link: 'https://pmfby.gov.in/',
  },
  {
    name: 'Soil Health Card Scheme',
    state: 'All India',
    category: 'Soil Health',
    description: 'Promotes balanced fertilizer use through periodic soil testing and crop-wise nutrient recommendations.',
    eligibility: 'All farmers can submit soil samples through local agriculture department channels.',
    documents: ['Identity Proof', 'Land Details', 'Soil Sample Information'],
    benefits: 'Soil health report card with fertilizer dosage guidance to improve productivity and reduce costs.',
    application_link: 'https://soilhealth.dac.gov.in/',
  },
  {
    name: 'Kisan Credit Card (KCC)',
    state: 'All India',
    category: 'Credit Support',
    description: 'Provides farmers with short-term credit for crop cultivation, allied activities, and post-harvest expenses.',
    eligibility: 'Individual farmers, joint borrowers, tenant farmers, and SHGs engaged in agriculture and allied sectors.',
    documents: ['Identity Proof', 'Address Proof', 'Land Records', 'Photographs'],
    benefits: 'Timely access to low-interest credit and interest subvention on prompt repayment.',
    application_link: 'https://www.myscheme.gov.in/schemes/kcc',
  },
  {
    name: 'Pradhan Mantri Krishi Sinchai Yojana (PMKSY)',
    state: 'All India',
    category: 'Irrigation',
    description: 'Improves irrigation efficiency and promotes micro-irrigation under the Per Drop More Crop component.',
    eligibility: 'Farmers with cultivable land eligible under state implementation guidelines.',
    documents: ['Aadhaar Card', 'Land Ownership Proof', 'Bank Details', 'Irrigation Layout Details'],
    benefits: 'Subsidy support for irrigation infrastructure and improved water-use efficiency.',
    application_link: 'https://pmksy.gov.in/',
  },
  {
    name: 'Paramparagat Krishi Vikas Yojana (PKVY)',
    state: 'All India',
    category: 'Organic Farming',
    description: 'Encourages cluster-based organic farming and certification support for better market linkage.',
    eligibility: 'Farmer groups willing to adopt organic farming practices in cluster mode.',
    documents: ['Identity Proof', 'Land Records', 'Farmer Group Details', 'Bank Account Details'],
    benefits: 'Financial support for organic inputs, certification, and value-chain development.',
    application_link: 'https://pgsindia-ncof.gov.in/',
  },
  {
    name: 'National Mission on Natural Farming (NMNF)',
    state: 'All India',
    category: 'Sustainable Farming',
    description: 'Promotes natural farming practices to reduce chemical input dependence and improve soil ecology.',
    eligibility: 'Farmers enrolled through state agriculture departments and designated implementation clusters.',
    documents: ['Farmer Registration', 'Land Details', 'Identity Proof'],
    benefits: 'Capacity building, demonstration support, and resource material for natural farming adoption.',
    application_link: 'https://agricoop.nic.in/',
  },
  {
    name: 'Rythu Bandhu Scheme',
    state: 'Telangana',
    category: 'Income Support',
    description: 'State support scheme offering investment assistance to farmers per acre for each crop season.',
    eligibility: 'Telangana land-owning farmers as per updated land records.',
    documents: ['Pattadar Passbook', 'Aadhaar Card', 'Bank Account Details'],
    benefits: 'Seasonal investment support credited directly to beneficiaries.',
    application_link: 'https://rythubandhu.telangana.gov.in/',
  },
  {
    name: 'KALIA Scheme',
    state: 'Odisha',
    category: 'Livelihood Support',
    description: 'Provides financial, cultivation, and livelihood support to small and marginal farmers, sharecroppers, and landless laborers.',
    eligibility: 'Eligible Odisha beneficiaries including small and marginal farmers and vulnerable cultivators.',
    documents: ['Aadhaar Card', 'Bank Account', 'Income Certificate', 'Land or Cultivation Proof'],
    benefits: 'Direct support for cultivation, livelihood, and insurance coverage under defined components.',
    application_link: 'https://kalia.odisha.gov.in/',
  },
  {
    name: 'Maharashtra Mukhyamantri Baliraja Mafi Yojana',
    state: 'Maharashtra',
    category: 'Loan Relief',
    description: 'State-level agricultural loan relief support for eligible farmers under notified criteria.',
    eligibility: 'Maharashtra farmers meeting state-announced crop loan eligibility conditions.',
    documents: ['Loan Account Statement', 'Aadhaar Card', 'Land Records', 'Bank Passbook'],
    benefits: 'Loan relief support for qualifying beneficiaries under state policy guidelines.',
    application_link: 'https://maharashtra.gov.in/',
  },
  {
    name: 'e-NAM (National Agriculture Market)',
    state: 'All India',
    category: 'Market Linkage',
    description: 'Digital trading platform that connects APMC mandis and improves price discovery for farmers.',
    eligibility: 'Farmers registered through participating mandis or state e-NAM onboarding channels.',
    documents: ['Identity Proof', 'Bank Account Details', 'Farmer Registration'],
    benefits: 'Wider market access, transparent bidding, and better price realization.',
    application_link: 'https://www.enam.gov.in/',
  },
  {
    name: 'PM Kisan Maandhan Yojana',
    state: 'All India',
    category: 'Pension',
    description: 'Voluntary pension scheme for small and marginal farmers with monthly pension after 60 years of age.',
    eligibility: 'Small and marginal farmers aged 18 to 40 years with cultivable land up to 2 hectares.',
    documents: ['Aadhaar Card', 'Bank Passbook', 'Land Records'],
    benefits: 'Assured monthly pension of Rs. 3,000 after age 60 under contribution-based model.',
    application_link: 'https://maandhan.in/',
  },
  {
    name: 'Sub-Mission on Agricultural Mechanization (SMAM)',
    state: 'All India',
    category: 'Farm Mechanization',
    description: 'Supports adoption of farm machinery through subsidies and custom hiring centers.',
    eligibility: 'Individual farmers, FPOs, cooperatives, and custom hiring centers as per state norms.',
    documents: ['Identity Proof', 'Land Records', 'Quotation of Equipment', 'Bank Details'],
    benefits: 'Capital subsidy for farm equipment and mechanization infrastructure.',
    application_link: 'https://agrimachinery.nic.in/',
  },
  {
    name: 'Rashtriya Krishi Vikas Yojana (RKVY-RAFTAAR)',
    state: 'All India',
    category: 'Agriculture Development',
    description: 'Supports states in agriculture and allied sector projects including innovation and agri-startups.',
    eligibility: 'State-approved project beneficiaries, agri-entrepreneurs, and farmer collectives as per project guidelines.',
    documents: ['Project Proposal', 'Identity Proof', 'Bank Details', 'Category Certificates if required'],
    benefits: 'Project grants, innovation support, and entrepreneurship promotion in agriculture.',
    application_link: 'https://rkvy.da.gov.in/',
  },
  {
    name: 'Namo Shetkari Mahasanman Nidhi Yojana',
    state: 'Maharashtra',
    category: 'Income Support',
    description: 'Maharashtra state top-up support for PM-KISAN beneficiaries to improve direct income assistance.',
    eligibility: 'Eligible PM-KISAN farmers in Maharashtra under state beneficiary list.',
    documents: ['PM-KISAN Registration', 'Aadhaar Card', 'Bank Account Details'],
    benefits: 'Additional direct financial support from state government.',
    application_link: 'https://maharashtra.gov.in/',
  },
  {
    name: 'YSR Rythu Bharosa',
    state: 'Andhra Pradesh',
    category: 'Income Support',
    description: 'State farmer assistance scheme supporting investment and livelihood needs for eligible cultivators.',
    eligibility: 'Eligible farmers and tenant cultivators in Andhra Pradesh under state criteria.',
    documents: ['Aadhaar Card', 'Land or Cultivation Proof', 'Bank Details'],
    benefits: 'Direct annual financial support through phased disbursement.',
    application_link: 'https://ysrrythubharosa.ap.gov.in/',
  },
  {
    name: 'Mukhyamantri Krishi Ashirwad Yojana',
    state: 'Jharkhand',
    category: 'Income Support',
    description: 'Provides per-acre support to eligible farmers in Jharkhand to reduce seasonal input stress.',
    eligibility: 'Eligible landholding farmers in Jharkhand as per notified records.',
    documents: ['Land Records', 'Identity Proof', 'Bank Account Details'],
    benefits: 'Per-acre direct support for agriculture input expenses.',
    application_link: 'https://mmkay.jharkhand.gov.in/',
  },
  {
    name: 'Bhavantar Bhugtan Yojana',
    state: 'Madhya Pradesh',
    category: 'Price Deficiency Payment',
    description: 'Compensates farmers for difference between market price and declared support benchmark for selected crops.',
    eligibility: 'Registered farmers selling notified crops in designated markets within state timelines.',
    documents: ['Farmer Registration', 'Sale Receipt', 'Bank Account Details', 'Identity Proof'],
    benefits: 'Price deficiency compensation credited directly to bank account.',
    application_link: 'https://mpkrishi.mp.gov.in/',
  },
];

export const seedSchemesIfEmpty = async (): Promise<void> => {
  // Idempotent seeding: upsert defaults so newly added seed entries appear in existing deployments too.
  let upsertedCount = 0;

  for (const seed of schemeSeeds) {
    await Scheme.findOneAndUpdate(
      { name: seed.name, state: seed.state },
      { $setOnInsert: seed },
      { upsert: true }
    );
    upsertedCount += 1;
  }

  console.log(`[seed] Ensured ${upsertedCount} default government schemes are present`);
};