import { create } from './zustand-mock';

export type LanguageCode = 'en' | 'hi' | 'mr' | 'gu' | 'bn';

interface LanguageState {
    language: LanguageCode;
    setLanguage: (lang: LanguageCode) => void;
    t: (key: string) => string;
}

const translations: Record<LanguageCode, Record<string, string>> = {
    en: {
        'nav.farmHealth': 'Farm Health',
        'nav.market': 'Market',
        'nav.tools': 'Tools',
        'nav.chat': 'Chat',
        'nav.schemes': 'Schemes',
        'nav.dashboard': 'Dashboard',
        'nav.login': 'Login',
        'nav.register': 'Register',
        'hero.title': 'Smart Farming for a Brighter Tomorrow',
        'hero.subtitle': 'AgroConnect empowers farmers with AI-driven insights, direct market access, and a supportive community.',
        'hero.getStarted': 'Get Started',
        'hero.madeInIndia': 'Made in India',
        'hero.aiPlatform': 'AI-Powered Platform',
        'dashboard.title': 'My Dashboard',
        'dashboard.subtitle': 'Overview of your farm, market activity, and notifications',
        'dashboard.farmHealth': 'Farm Health',
        'dashboard.activeListings': 'Active Listings',
        'dashboard.toolsListed': 'Tools Listed',
        'dashboard.notifications': 'Notifications',
        'market.intelligence': 'Market Intelligence',
        'market.buySell': 'Buy & Sell',
        'market.title': 'AgroConnect Market',
        'market.intelHeader': 'Crop Market Intelligence',
        'market.intelSubtitle': 'Real-time price tracking, demand analysis, and AI-powered predictions',
        'market.livePrices': 'Live Prices',
        'market.trends': 'Trends',
        'market.predictions': 'AI Predictions',
        'market.insights': 'Insights',
        'dashboard.weather': 'Weather',
        'dashboard.temp': 'Temp',
        'dashboard.humidity': 'Humidity',
        'dashboard.wind': 'Wind',
        'dashboard.rainfall': 'Rainfall',
        'dashboard.alerts': 'Active Alerts',
        'dashboard.noAlerts': 'No active alerts',
        'dashboard.sales': 'Sales Overview',
        'dashboard.prices': 'Typical Market Rates',
        'dashboard.recentNav': 'Recent Notifications',
        'dashboard.pending': 'Pending Bookings',
        'dashboard.noPending': 'No pending bookings',
        'dashboard.quick': 'Quick Actions',
        'dashboard.checkCrops': 'Check Crops',
        'dashboard.newListing': 'New Listing',
        'dashboard.listTool': 'List Tool',
        'dashboard.messages': 'Messages',
        'dashboard.cropStatus': 'Crop Health Status',
        'dashboard.sustainable': 'Sustainable Farming',
        'dashboard.joinMovement': 'Join the movement towards a greener, smarter future with AgroConnect.',
        'farm.title': 'Farm Health & Monitoring',
        'farm.subtitle': 'AI-powered crop analysis and field monitoring',
        'schemes.title': 'Government Schemes',
        'schemes.subtitle': 'Discover and apply for agricultural subsidies and benefits',
        'tools.title': 'Tools & Machinery Lending',
        'tools.subtitle': 'Rent or lend farm machinery within your community',
        'chat.title': 'Farmer Community',
        'chat.subtitle': 'Connect, share, and grow together',
        'farm.healthMonitoring': 'Farm Health Monitoring',
        'farm.overview': 'Overview',
        'farm.aiAnalysis': 'AI Analysis',
        'farm.weather': 'Weather',
        'farm.soilData': 'Soil Data',
        'farm.lastChecked': 'Last Checked',
        'farm.issues': 'Issues',
        'farm.recommendations': 'Recommendations',
        'farm.aiActions': 'AI-Powered Actions',
        'farm.analyzeCrop': 'Analyze Crop Image',
        'farm.checkWeather': 'Check Weather',
        'farm.soilAnalysis': 'Soil Analysis',
        'farm.fertilizerGuide': 'Fertilizer Guide',
        'farm.uploadCrop': 'Upload Crop Image',
        'farm.diseasesDetection': 'AI Crop Disease Check',
        'farm.plantDoctor': 'Plant Doctor',
        'farm.analysisComplete': 'Analysis Complete',
        'farm.detectedIssue': 'Detected Issue',
        'farm.affectedArea': 'Affected Area',
        'farm.confidence': 'Confidence',
        'farm.severity': 'Severity',
        'farm.soilComposition': 'Soil Composition',
        'farm.phLevel': 'pH Level',
        'farm.nitrogen': 'Nitrogen (N)',
        'farm.phosphorus': 'Phosphorus (P)',
        'farm.potassium': 'Potassium (K)',
        'farm.moisture': 'Moisture',
        'farm.soilRecommendations': 'Soil Recommendations',
        'farm.resolve': 'Resolve',
        'farm.fireAlert': 'Fire Alert',
        'farm.theftAlert': 'Theft Alert',
        'farm.diseaseAlert': 'Disease Alert',
        'farm.weatherAlert': 'Weather Alert',
        'farm.pestAlert': 'Pest Alert',
        'farm.goodHealth': 'Healthy Status',
        'farm.badHealth': 'Diseased/At-Risk',
        'farm.detectedLabel': 'Detected Disease/Condition',
        'farm.preventiveMeasures': 'Preventive Measures',
        'farm.analyse': 'Analyse',
        'farm.selectPlant': 'Select Plant Type',
        'farm.choosePlant': 'Choose a plant...',
        'farm.uploadBtn': 'Upload Image',
        'farm.cameraBtn': 'Take Photo',
        'farm.uploadInstruction': 'Take a clear photo of the affected plant part and our AI will detect diseases, pests, and nutrient deficiencies.',
        'farm.clickUpload': 'Click to upload or drag and drop',
        'farm.uploadLimit': 'Supports JPG, PNG up to 10MB',
        'farm.analyzing': 'Analyzing...',
        'farm.analyzeAI': 'Analyze with AI',
        'farm.analyseAnother': 'Analyse Another',
        'tools.toolsLand': 'Tools & Land Lending',
        'tools.rentFarm': 'Rent farm equipment and land from fellow farmers',
        'tools.farmTools': 'Farm Tools',
        'tools.farmland': 'Farmland',
        'tools.myBookings': 'My Bookings',
        'tools.listYour': 'List Your Tool/Land',
        'tools.searchTools': 'Search tools or location...',
        'tools.category': 'Category',
        'tools.allTools': 'All Tools',
        'tools.tractors': 'Tractors',
        'tools.tillers': 'Tillers',
        'tools.sprayers': 'Sprayers',
        'tools.harvesters': 'Harvesters',
        'tools.other': 'Other',
        'tools.new': 'New',
        'tools.excellent': 'Excellent',
        'tools.good': 'Good',
        'tools.fair': 'Fair',
        'tools.dailyRate': 'Daily Rate',
        'tools.security': 'Security',
        'tools.bookNow': 'Book Now',
        'tools.inquireNow': 'Inquire Now',
        'tools.size': 'Size',
        'tools.soilType': 'Soil Type',
        'tools.monthlyRent': 'Monthly Rent',
        'tools.waterSource': 'Water Source',
        'tools.total': 'Total',
        'tools.payNow': 'Pay Now',
        'tools.paid': 'Paid',
        'tools.noBookings': 'No bookings yet',
        'tools.startBooking': 'Start by booking a tool or land',
        'tools.startDate': 'Start Date',
        'tools.endDate': 'End Date',
        'tools.confirmBooking': 'Confirm Booking Request',
        'tools.sendInquiry': 'Send Inquiry & Chat',
        'tools.noteInquiry': 'Note: Clicking "Send Inquiry" will create an inquiry request and open a chat with the landowner to discuss details.',
        'tools.createListing': 'Create Tool Listing',
        'tools.toolName': 'Tool Name',
        'tools.landTitle': 'Land Title',
        'schemes.total': 'Total Schemes',
        'schemes.myApplications': 'My Applications',
        'schemes.bookmarked': 'Bookmarked',
        'schemes.farmersBenefited': 'Farmers Benefited',
        'schemes.allSchemes': 'All Schemes',
        'schemes.assistant': 'Scheme Assistant',
        'schemes.search': 'Search schemes...',
        'schemes.state': 'State',
        'schemes.category': 'Category',
        'schemes.viewDetails': 'View Details',
        'schemes.applyNow': 'Apply Now',
        'schemes.deadline': 'Deadline',
        'schemes.central': 'Central',
        'schemes.stateSmall': 'State',
        'schemes.stateScheme': 'State Scheme',
        'schemes.centralScheme': 'Central Scheme',
        'schemes.noBookmarks': 'No bookmarked schemes',
        'schemes.noApplications': 'No applications yet',
        'schemes.eligibility': 'Eligibility Criteria',
        'schemes.benefits': 'Benefits',
        'schemes.documents': 'Required Documents',
        'schemes.process': 'Application Process',
        'schemes.assistantTitle': 'Scheme Assistant',
        'schemes.askAssistant': 'Ask about schemes...',
        'hero.feature.farmHealth': 'AI-Powered Farm Health',
        'hero.feature.farmHealthDesc': 'Detect diseases, analyze soil, and get smart recommendations',
        'hero.feature.market': 'Market Intelligence',
        'hero.feature.marketDesc': 'Real-time crop prices and demand predictions',
        'hero.feature.tools': 'Tools & Land Lending',
        'hero.feature.toolsDesc': 'Rent farm equipment and land from nearby farmers',
        'hero.feature.marketplace': 'Direct Marketplace',
        'hero.feature.marketplaceDesc': 'Sell crops directly to buyers without middlemen',
        'hero.feature.community': 'Farmer Community',
        'hero.feature.communityDesc': 'Connect with farmers, share knowledge, and chat',
        'hero.feature.schemes': 'Government Schemes',
        'hero.feature.schemesDesc': 'Access subsidies and scheme information easily',
        'hero.stats.farmers': 'Registered Farmers',
        'hero.stats.sales': 'Crop Sales',
        'hero.stats.tools': 'Tools Listed',
        'hero.stats.states': 'States Covered',
        'market.directMarketplace': 'Direct Crop Marketplace',
        'market.buySellSubtitle': 'Buy and sell crops directly - no middlemen, better prices',
        'market.trending': 'Trending Crops',
        'market.browseCrops': 'Browse Crops',
        'market.myListings': 'My Listings',
        'market.sellYourCrop': 'Sell Your Crop',
        'market.searchPlaceholder': 'Search crops or location...',
        'market.organicOnly': 'Organic Only',
        'market.per': 'per',
        'market.available': 'available',
        'market.addCart': 'Add to Cart',
        'market.chat': 'Chat',
        'market.minOrder': 'Min Order',
        'market.organic': 'Organic',
        'market.quality': 'Quality',
        'market.searchCrops': 'Search crops...',
        'market.filterBy': 'Filter by',
        'market.allCrops': 'All Crops',
        'market.highDemand': 'High Demand',
        'market.priceRising': 'Price Rising',
        'market.priceFalling': 'Price Falling',
        'market.vsLastMonth': 'vs last month',
        'market.demand': 'demand',
        'market.supply': 'supply',
        'market.priceHistory': 'Price History',
        'market.priceComparison': 'Price Comparison',
        'market.marketDistribution': 'Market Distribution',
        'market.aiAnalysisDesc': 'Our AI analyzes historical data, weather patterns, and market trends to predict future prices with high accuracy.',
        'market.current': 'Current',
        'market.predicted': 'Predicted',
        'market.confidence': 'Confidence',
        'market.expectedToRise': 'Expected to rise by',
        'market.expectedToFall': 'Expected to fall by',
        'market.aiRecommendation': 'AI Recommendation',
        'market.aiRecommendationDesc': 'Based on current market trends and predictions, we provide smart recommendations for buying and selling.',
        'market.impact': 'impact',
        'market.categoryLabel': 'Category',
        'market.addListingTitle': 'Sell Your Crop',
        'market.cropNameLabel': 'Crop Name',
        'market.varietyLabel': 'Variety',
        'market.pricePerUnitLabel': 'Price per unit (₹)',
        'market.totalQuantityLabel': 'Total Quantity',
        'market.minOrderQuantityLabel': 'Min Order Quantity',
        'market.locationLabel': 'Location',
        'market.organicCheckbox': 'This is organic produce',
        'market.descriptionLabel': 'Description',
        'market.createListingBtn': 'Create Listing',
        'market.contactSeller': 'Contact Seller',
        'market.reviews': 'reviews',
        'market.wishlistEmpty': 'Your wishlist is empty',
        'market.saveCropsInterest': "Save crops you're interested in",
        'market.uploadCropImage': 'Click to upload crop image',
        'market.cropNamePlaceholder': 'Crop Name',
        'market.varietyPlaceholder': 'Variety',
        'market.categoryPlaceholder': 'Category',
        'market.pricePerUnitPlaceholder': 'Price per unit (₹)',
        'market.unitPlaceholder': 'Unit',
        'market.perKg': 'per kg',
        'market.perQuintal': 'per quintal',
        'market.perTon': 'per ton',
        'market.totalQuantityPlaceholder': 'Total Quantity',
        'market.minOrderQuantityPlaceholder': 'Min Order Quantity',
        'market.locationPlaceholder': 'Location',
        'market.organicProduceLabel': 'This is organic produce',
        'market.descriptionPlaceholder': 'Description',
        'market.contactFarmer': 'Contact Seller',
        'market.startChat': 'Start Chat',
        'market.callFarmer': 'Call Farmer',
        'market.addToCart': 'Add to Cart',
        'market.totalPrice': 'Total Price',
        'market.cancel': 'Cancel',
        'market.confirmAdd': 'Confirm Add',
        'market.quantity': 'Quantity',
        'footer.motto': 'Empowering farmers with technology, market access, and community support for a sustainable future.',
        'footer.quickLinks': 'Quick Links',
        'footer.support': 'Support',
        'footer.stayUpdated': 'Stay Updated',
        'footer.newsletterDesc': 'Subscribe to our newsletter for the latest updates on schemes, market prices, and farming tips.',
        'footer.newsletterPlaceholder': 'Enter your email',
        'footer.helpline': 'Helpline',
        'footer.rights': 'All rights reserved.',
        'footer.madeWith': 'Made with',
        'footer.forFarmers': 'for Indian Farmers',
        'dashboard.yourLocation': 'Your Location',
        'dashboard.alert': 'Alert',
        'dashboard.perQuintal': '/quintal'
    },
    hi: {
        'nav.farmHealth': 'खेत स्वास्थ्य',
        'nav.market': 'बाजार',
        'nav.tools': 'उपकरण',
        'nav.chat': 'चैट',
        'nav.schemes': 'योजनाएं',
        'nav.dashboard': 'डैशबोर्ड',
        'nav.login': 'लॉगिन',
        'nav.register': 'पंजीकरण',
        'hero.title': 'बेहतर कल के लिए स्मार्ट खेती',
        'hero.subtitle': 'AgroConnect किसानों को AI-आधारित अंतर्दृष्टि, सीधी बाजार पहुंच और एक सहायक समुदाय के साथ सशक्त बनाता है।',
        'hero.getStarted': 'शुरू करें',
        'hero.madeInIndia': 'भारत में निर्मित',
        'hero.aiPlatform': 'AI-संचालित प्लेटफॉर्म',
        'dashboard.title': 'मेरा डैशबोर्ड',
        'dashboard.subtitle': 'आपके खेत, बाजार गतिविधि और सूचनाओं का अवलोकन',
        'dashboard.farmHealth': 'खेत स्वास्थ्य',
        'dashboard.activeListings': 'सक्रिय लिस्टिंग',
        'dashboard.toolsListed': 'सूचीबद्ध उपकरण',
        'dashboard.notifications': 'सूचनाएं',
        'market.intelligence': 'बाजार खुफिया',
        'market.buySell': 'खरीदें और बेचें',
        'market.title': 'AgroConnect बाजार',
        'market.intelHeader': 'फसल बाजार खुफिया',
        'market.intelSubtitle': 'वास्तविक समय मूल्य ट्रैकिंग, मांग विश्लेषण और AI-संचालित भविष्यवाणियां',
        'market.livePrices': 'लाइव कीमतें',
        'market.trends': 'रुझान',
        'market.predictions': 'AI भविष्यवाणियां',
        'market.insights': 'अंतर्दृष्टि',
        'dashboard.weather': 'मौसम',
        'dashboard.temp': 'तापमान',
        'dashboard.humidity': 'नमी',
        'dashboard.wind': 'हवा',
        'dashboard.rainfall': 'बारिश',
        'dashboard.alerts': 'सक्रिय अलर्ट',
        'dashboard.noAlerts': 'कोई सक्रिय अलर्ट नहीं',
        'dashboard.sales': 'बिक्री अवलोकन',
        'dashboard.prices': 'वर्तमान बाजार भाव',
        'dashboard.recentNav': 'हालिया सूचनाएं',
        'dashboard.pending': 'लंबित बुकिंग',
        'dashboard.noPending': 'कोई लंबित बुकिंग नहीं',
        'dashboard.quick': 'त्वरित कार्रवाई',
        'dashboard.checkCrops': 'फसलें जांचें',
        'dashboard.newListing': 'नई लिस्टिंग',
        'dashboard.listTool': 'उपकरण जोड़ें',
        'dashboard.messages': 'संदेश',
        'dashboard.cropStatus': 'फसल स्वास्थ्य स्थिति',
        'dashboard.sustainable': 'सतत कृषि',
        'dashboard.joinMovement': 'AgroConnect के साथ हरित, स्मार्ट भविष्य की ओर आंदोलन में शामिल हों।',
        'farm.title': 'खेत स्वास्थ्य और निगरानी',
        'farm.subtitle': 'AI-संचालित फसल विश्लेषण और क्षेत्र निगरानी',
        'schemes.title': 'सरकारी योजनाएं',
        'schemes.subtitle': 'कृषि सब्सिडी और लाभों की खोज करें और आवेदन करें',
        'tools.title': 'उपकरण और मशीनरी उधार',
        'tools.subtitle': 'अपने समुदाय के भीतर कृषि मशीनरी किराए पर लें या दें',
        'chat.title': 'किसान समुदाय',
        'chat.subtitle': 'जुड़ें, साझा करें और साथ बढ़ें',
        'farm.healthMonitoring': 'खेत स्वास्थ्य निगरानी',
        'farm.overview': 'अवलोकन',
        'farm.aiAnalysis': 'AI विश्लेषण',
        'farm.weather': 'मौसम',
        'farm.soilData': 'मिट्टी का डेटा',
        'farm.lastChecked': 'अंतिम जांच',
        'farm.issues': 'समस्याएं',
        'farm.recommendations': 'सिफारिशें',
        'farm.aiActions': 'AI-संचालित क्रियाएं',
        'farm.analyzeCrop': 'फसल छवि का विश्लेषण करें',
        'farm.checkWeather': 'मौसम की जांच करें',
        'farm.soilAnalysis': 'मिट्टी का विश्लेषण',
        'farm.fertilizerGuide': 'उर्वरक गाइड',
        'farm.uploadCrop': 'फसल की छवि अपलोड करें',
        'farm.diseasesDetection': 'AI फसल रोग जांच',
        'farm.plantDoctor': 'प्लांट डॉक्टर',
        'farm.analysisComplete': 'विश्लेषण पूरा हुआ',
        'farm.detectedIssue': 'पाई गई समस्या',
        'farm.affectedArea': 'प्रभावित क्षेत्र',
        'farm.confidence': 'आत्मविश्वास',
        'farm.severity': 'गंभीरता',
        'farm.soilComposition': 'मिट्टी की संरचना',
        'farm.phLevel': 'pH स्तर',
        'farm.nitrogen': 'नाइट्रोजन (N)',
        'farm.phosphorus': 'फास्फोरस (P)',
        'farm.potassium': 'पोटेशियम (K)',
        'farm.moisture': 'नमी',
        'farm.soilRecommendations': 'मिट्टी की सिफारिशें',
        'farm.resolve': 'हल करें',
        'farm.fireAlert': 'अग्नि अलर्ट',
        'farm.theftAlert': 'चोरी अलर्ट',
        'farm.diseaseAlert': 'रोग अलर्ट',
        'farm.weatherAlert': 'मौसम अलर्ट',
        'farm.pestAlert': 'कीट अलर्ट',
        'farm.goodHealth': 'स्वस्थ स्थिति',
        'farm.badHealth': 'रोगग्रस्त/जोखिम में',
        'farm.detectedLabel': 'पता चली बीमारी/स्थिति',
        'farm.preventiveMeasures': 'निवारक उपाय',
        'farm.analyse': 'विश्लेषण करें',
        'farm.selectPlant': 'पौधे का प्रकार चुनें',
        'farm.choosePlant': 'पौधा चुनें...',
        'farm.uploadBtn': 'छवि अपलोड करें',
        'farm.cameraBtn': 'फोटो लें',
        'farm.uploadInstruction': 'प्रभावित पौधे के हिस्से की एक साफ फोटो लें और हमारा एआई बीमारियों, कीटों और पोषक तत्वों की कमी का पता लगाएगा।',
        'farm.clickUpload': 'अपलोड करने के लिए क्लिक करें या खींचें और छोड़ें',
        'farm.uploadLimit': '10MB तक JPG, PNG का समर्थन करता है',
        'farm.analyzing': 'विश्लेषण किया जा रहा है...',
        'farm.analyzeAI': 'एआई के साथ विश्लेषण करें',
        'farm.analyseAnother': 'एक और विश्लेषण करें',
        'tools.toolsLand': 'उपकरण and भूमि उधार',
        'tools.rentFarm': 'साथी किसानों से कृषि उपकरण और भूमि किराए पर लें',
        'tools.farmTools': 'कृषि उपकरण',
        'tools.farmland': 'कृषि भूमि',
        'tools.myBookings': 'मेरी बुकिंग',
        'tools.listYour': 'अपना उपकरण/भूमि सूचीबद्ध करें',
        'tools.searchTools': 'उपकरण या स्थान खोजें...',
        'tools.category': 'श्रेणी',
        'tools.allTools': 'सभी उपकरण',
        'tools.tractors': 'ट्रैक्टर',
        'tools.tillers': 'टिलर',
        'tools.sprayers': 'स्प्रेयर',
        'tools.harvesters': 'हार्वेस्टर',
        'tools.other': 'अन्य',
        'tools.new': 'नया',
        'tools.excellent': 'उत्कृष्ट',
        'tools.good': 'अच्छा',
        'tools.fair': 'ठीक',
        'tools.dailyRate': 'दैनिक दर',
        'tools.security': 'सुरक्षा',
        'tools.bookNow': 'अभी बुक करें',
        'tools.inquireNow': 'अभी पूछताछ करें',
        'tools.size': 'आकार',
        'tools.soilType': 'मिट्टी का प्रकार',
        'tools.monthlyRent': 'मासिक किराया',
        'tools.waterSource': 'जल स्रोत',
        'tools.total': 'कुल',
        'tools.payNow': 'अभी भुगतान करें',
        'tools.paid': 'भुगतान किया गया',
        'tools.noBookings': 'अभी तक कोई बुकिंग नहीं',
        'tools.startBooking': 'उपकरण या भूमि बुक करके शुरुआत करें',
        'tools.startDate': 'प्रारंभ तिथि',
        'tools.endDate': 'अंतिम तिथि',
        'tools.confirmBooking': 'बुकिंग अनुरोध की पुष्टि करें',
        'tools.sendInquiry': 'पूछताछ और चैट भेजें',
        'tools.noteInquiry': 'नोट: "पूछताछ भेजें" पर क्लिक करने से एक पूछताछ अनुरोध तैयार होगा और भूमि मालिक के साथ एक चैट खुल जाएगी ताकि आप विवरण पर चर्चा कर सकें।',
        'tools.createListing': 'उपकरण लिस्टिंग बनाएं',
        'tools.toolName': 'उपकरण का नाम',
        'tools.landTitle': 'भूमि शीर्षक',
        'schemes.total': 'कुल योजनाएं',
        'schemes.myApplications': 'मेरे आवेदन',
        'schemes.bookmarked': 'बुकमार्क किया गया',
        'schemes.farmersBenefited': 'लाभान्वित किसान',
        'schemes.allSchemes': 'सभी योजनाएं',
        'schemes.assistant': 'योजना सहायक',
        'schemes.search': 'योजनाएं खोजें...',
        'schemes.state': 'राज्य',
        'schemes.category': 'श्रेणी',
        'schemes.viewDetails': 'विवरण देखें',
        'schemes.applyNow': 'अभी आवेदन करें',
        'schemes.deadline': 'अंतिम तिथि',
        'schemes.central': 'केंद्रीय',
        'schemes.stateSmall': 'राज्य',
        'schemes.stateScheme': 'राज्य योजना',
        'schemes.centralScheme': 'केंद्रीय योजना',
        'schemes.noBookmarks': 'कोई बुकमार्क की गई योजना नहीं',
        'schemes.noApplications': 'अभी तक कोई आवेदन नहीं',
        'schemes.eligibility': 'पात्रता मापदंड',
        'schemes.benefits': 'लाभ',
        'schemes.documents': 'आवश्यक दस्तावेज',
        'schemes.process': 'आवेदन प्रक्रिया',
        'schemes.assistantTitle': 'योजना सहायक',
        'schemes.askAssistant': 'योजनाओं के बारे में पूछें...',
        'hero.feature.farmHealth': 'AI-संचालित खेत स्वास्थ्य',
        'hero.feature.farmHealthDesc': 'रोगों का पता लगाएं, मिट्टी का विश्लेषण करें और स्मार्ट अनुशंसाएं प्राप्त करें',
        'hero.feature.market': 'बाजार इंटेलिजेंस',
        'hero.feature.marketDesc': 'वास्तविक समय में फसल की कीमतें और मांग की भविष्यवाणी',
        'hero.feature.tools': 'उपकरण और भूमि ऋण',
        'hero.feature.toolsDesc': 'आस-पास के किसानों से कृषि उपकरण और भूमि किराए पर लें',
        'hero.feature.marketplace': 'प्रत्यक्ष बाजार',
        'hero.feature.marketplaceDesc': 'बिना बिचौलियों के उत्पाद सीधे खरीदारों को बेचें',
        'hero.feature.community': 'किसान समुदाय',
        'hero.feature.communityDesc': 'किसानों से जुड़ें, ज्ञान साझा करें और चैट करें',
        'hero.feature.schemes': 'सरकारी योजनाएं',
        'hero.feature.schemesDesc': 'सब्सिडी और योजनाओं की जानकारी आसानी से प्राप्त करें',
        'hero.stats.farmers': 'पंजीकृत किसान',
        'hero.stats.sales': 'फसल की बिक्री',
        'hero.stats.tools': 'सूचीबद्ध उपकरण',
        'hero.stats.states': 'कवर किए गए राज्य',
        'market.directMarketplace': 'प्रत्यक्ष फसल बाजार',
        'market.buySellSubtitle': 'फसलें सीधे खरीदें और बेचें - कोई बिचौलिया नहीं, बेहतर कीमतें',
        'market.trending': 'प्रचलित फसलें',
        'market.browseCrops': 'फसलें देखें',
        'market.myListings': 'मेरी लिस्टिंग',
        'market.sellYourCrop': 'अपनी फसल बेचें',
        'market.searchPlaceholder': 'फसलें या स्थान खोजें...',
        'market.organicOnly': 'केवल जैविक',
        'market.per': 'प्रति',
        'market.available': 'उपलब्ध',
        'market.addCart': 'कार्ट में जोड़ें',
        'market.chat': 'चैट करें',
        'market.minOrder': 'न्यूनतम ऑर्डर',
        'market.organic': 'जैविक',
        'market.quality': 'गुणवत्ता',
        'market.searchCrops': 'फसलें खोजें...',
        'market.filterBy': 'दुआरा फ़िल्टर',
        'market.allCrops': 'सभी फसलें',
        'market.highDemand': 'उच्च मांग',
        'market.priceRising': 'कीमतें बढ़ रही हैं',
        'market.priceFalling': 'कीमतें गिर रही हैं',
        'market.vsLastMonth': 'पिछले महीने के मुकाबले',
        'market.demand': 'मांग',
        'market.supply': 'आपूर्ति',
        'market.priceHistory': 'मूल्य इतिहास',
        'market.priceComparison': 'मूल्य तुलना',
        'market.marketDistribution': 'बाजार वितरण',
        'market.aiAnalysisDesc': 'हमारा AI उच्च सटीकता के साथ भविष्य की कीमतों की भविष्यवाणी करने के लिए ऐतिहासिक डेटा, मौसम पैटर्न और बाजार के रुझानों का विश्लेषण करता है।',
        'market.current': 'वर्तमान',
        'market.predicted': 'अनुमानित',
        'market.confidence': 'आत्मविश्वास',
        'market.expectedToRise': 'बढ़ने की उम्मीद है',
        'market.expectedToFall': 'गिरने की उम्मीद है',
        'market.aiRecommendation': 'AI अनुशंसा',
        'market.aiRecommendationDesc': 'वर्तमान बाजार के रुझानों और भविष्यवाणियों के आधार पर, हम खरीदने और बेचने के लिए स्मार्ट अनुशंसाएं प्रदान करते हैं।',
        'market.impact': 'प्रभाव',
        'market.categoryLabel': 'श्रेणी',
        'market.addListingTitle': 'अपनी फसल बेचें',
        'market.cropNameLabel': 'फसल का नाम',
        'market.varietyLabel': 'किस्म',
        'market.pricePerUnitLabel': 'प्रति इकाई मूल्य (₹)',
        'market.totalQuantityLabel': 'कुल मात्रा',
        'market.minOrderQuantityLabel': 'न्यूनतम ऑर्डर मात्रा',
        'market.locationLabel': 'स्थान',
        'market.organicCheckbox': 'यह जैविक उत्पाद है',
        'market.descriptionLabel': 'विवरण',
        'market.createListingBtn': 'लिस्टिंग बनाएं',
        'market.contactSeller': 'विक्रेता से संपर्क करें',
        'market.reviews': 'समीक्षाएं',
        'footer.motto': 'एक स्थायी भविष्य के लिए प्रौद्योगिकी, बाजार पहुंच और सामुदायिक समर्थन के साथ किसानों को सशक्त बनाना।',
        'footer.quickLinks': 'त्वरित लिंक',
        'footer.support': 'सपोर्ट',
        'footer.stayUpdated': 'अपडेट रहें',
        'footer.newsletterDesc': 'योजनाओं, बाजार कीमतों और खेती के सुझावों पर नवीनतम अपडेट के लिए हमारे न्यूज़लेटर की सदस्यता लें।',
        'footer.newsletterPlaceholder': 'अपना ईमेल दर्ज करें',
        'footer.helpline': 'हेल्पलाइन',
        'footer.rights': 'सर्वाधिकार सुरक्षित।',
        'footer.madeWith': 'बनाया गया',
        'footer.forFarmers': 'भारतीय किसानों के लिए',
        'dashboard.yourLocation': 'आपका स्थान',
        'dashboard.alert': 'सचेत',
        'dashboard.perQuintal': '/क्विंटल'
    },
    mr: {
        'nav.farmHealth': 'शेत आरोग्य',
        'nav.market': 'बाजार',
        'nav.tools': 'साधने',
        'nav.chat': 'चॅट',
        'nav.schemes': 'योजना',
        'nav.dashboard': 'डॅशबोर्ड',
        'nav.login': 'लॉगिन',
        'nav.register': 'नोंदणी',
        'hero.title': 'उद्याच्या चांगल्या भविष्यासाठी स्मार्ट शेती',
        'hero.subtitle': 'AgroConnect शेतकऱ्यांना AI-आधारित माहिती, थेट बाजारपेठ आणि एक सहाय्यक समुदाय याद्वारे सक्षम करते.',
        'hero.getStarted': 'सुरू करा',
        'hero.madeInIndia': 'भारतात निर्मित',
        'hero.aiPlatform': 'AI-आधारित प्लॅटफॉर्म',
        'dashboard.title': 'माझा डॅशबोर्ड',
        'dashboard.subtitle': 'तुमची शेती, बाजारपेठेतील हालचाली आणि सूचनांचा आढावा',
        'dashboard.farmHealth': 'शेत आरोग्य',
        'dashboard.activeListings': 'सक्रिय यादी',
        'dashboard.toolsListed': 'सूचीबद्ध साधने',
        'dashboard.notifications': 'सूचना',
        'market.intelligence': 'बाजार माहिती',
        'market.buySell': 'खरेदी आणि विक्री',
        'market.title': 'AgroConnect बाजार',
        'market.intelHeader': 'पीक बाजार माहिती',
        'market.intelSubtitle': 'रिअल-टाइम किंमत ट्रॅकिंग, मागणी विश्लेषण आणि AI-आधारित अंदाज',
        'market.livePrices': 'थेट किमती',
        'market.trends': 'कल',
        'market.predictions': 'AI अंदाज',
        'market.insights': 'अंतर्दृष्टी',
        'dashboard.weather': 'हवामान',
        'dashboard.temp': 'तापमान',
        'dashboard.humidity': 'आद्रता',
        'dashboard.wind': 'वारा',
        'dashboard.rainfall': 'पाऊस',
        'dashboard.alerts': 'सक्रिय अलर्ट',
        'dashboard.noAlerts': 'कोणतेही सक्रिय अलर्ट नाहीत',
        'dashboard.sales': 'विक्री आढावा',
        'dashboard.prices': 'सध्याचे बाजार भाव',
        'dashboard.recentNav': 'नुकत्याच आलेल्या सूचना',
        'dashboard.pending': 'प्रलंबित बुकिंग',
        'dashboard.noPending': 'कोणतीही प्रलंबित बुकिंग नाही',
        'dashboard.quick': 'त्वरित कृती',
        'dashboard.checkCrops': 'पिके तपासा',
        'dashboard.newListing': 'नवीन यादी',
        'dashboard.listTool': 'साधन जोडा',
        'dashboard.messages': 'संदेश',
        'dashboard.cropStatus': 'पीक आरोग्य स्थिती',
        'dashboard.sustainable': 'शाश्वत शेती',
        'dashboard.joinMovement': 'AgroConnect सह अधिक हिरव्या आणि स्मार्ट भविष्यासाठी चळवळीत सामील व्हा.',
        'farm.title': 'शेत आरोग्य आणि देखरेख',
        'farm.subtitle': 'AI-आधारित पीक विश्लेषण आणि देखरेख',
        'schemes.title': 'शासकीय योजना',
        'schemes.subtitle': 'कृषी अनुदान आणि फायद्यांचा शोध घ्या आणि अर्ज करा',
        'tools.title': 'साधने आणि यंत्रसामग्री कर्ज',
        'tools.subtitle': 'तुमच्या समुदायात शेतीची यंत्रसामग्री भाड्याने घ्या किंवा द्या',
        'chat.title': 'शेतकरी समुदाय',
        'chat.subtitle': 'जोडले जा, सामायिक करा आणि एकत्र वाढा',
        'farm.healthMonitoring': 'शेत आरोग्य निरीक्षण',
        'farm.overview': 'आढावा',
        'farm.aiAnalysis': 'AI विश्लेषण',
        'farm.weather': 'हवामान',
        'farm.soilData': 'माती डेटा',
        'farm.lastChecked': 'शेवटची तपासणी',
        'farm.issues': 'समस्या',
        'farm.recommendations': 'शिफारसी',
        'farm.aiActions': 'AI-सक्षम कृती',
        'farm.analyzeCrop': 'पीक चित्राचे विश्लेषण करा',
        'farm.checkWeather': 'हवामान तपासा',
        'farm.soilAnalysis': 'माती विश्लेषण',
        'farm.fertilizerGuide': 'खत मार्गदर्शक',
        'farm.uploadCrop': 'पीक चित्र अपलोड करा',
        'farm.diseasesDetection': 'AI पीक रोग शोध',
        'farm.plantDoctor': 'प्लांट डॉक्टर',
        'farm.analysisComplete': 'विश्लेषण पूर्ण झाले',
        'farm.detectedIssue': 'आढळलेली समस्या',
        'farm.affectedArea': 'प्रभावित क्षेत्र',
        'farm.confidence': 'विश्वास',
        'farm.severity': 'गंभीरता',
        'farm.soilComposition': 'मातीची रचना',
        'farm.phLevel': 'pH पातळी',
        'farm.nitrogen': 'नायट्रोजन (N)',
        'farm.phosphorus': 'फॉस्फरस (P)',
        'farm.potassium': 'पोटॅशियम (K)',
        'farm.moisture': 'ओलावा',
        'farm.soilRecommendations': 'माती शिफारसी',
        'farm.resolve': 'निकाली काढा',
        'farm.fireAlert': 'आगीचा इशारा',
        'farm.theftAlert': 'चोरीचा इशारा',
        'farm.diseaseAlert': 'रोगाचा इशारा',
        'farm.weatherAlert': 'हवामानाचा इशारा',
        'farm.pestAlert': 'कीड इशारा',
        'farm.goodHealth': 'निरोगी स्थिती',
        'farm.badHealth': 'रोगग्रस्त/धोक्यात',
        'farm.detectedLabel': 'ओळखलेला रोग/स्थिती',
        'farm.preventiveMeasures': 'प्रतिबंधात्मक उपाय',
        'farm.analyse': 'विश्लेषण करा',
        'farm.selectPlant': 'रोपाचा प्रकार निवडा',
        'farm.choosePlant': 'रोप निवडा...',
        'farm.uploadBtn': 'चित्र अपलोड करा',
        'farm.cameraBtn': 'फोटो काढा',
        'farm.uploadInstruction': 'बाधित वनस्पतीच्या भागाचा स्पष्ट फोटो घ्या आणि आमचे एआय रोग, कीड आणि पोषक तत्वांच्या कमतरतेचा शोध घेतील।',
        'farm.clickUpload': 'अपलोड करण्यासाठी क्लिक करा किंवा ओढा आणि सोडा',
        'farm.uploadLimit': '10MB पर्यंत JPG, PNG ला सपोर्ट करते',
        'farm.analyzing': 'विश्लेषण होत आहे...',
        'farm.analyzeAI': 'एआय सह विश्लेषण करा',
        'farm.analyseAnother': 'आणखी एक विश्लेषण करा',
        'tools.toolsLand': 'साधने आणि जमीन कर्ज',
        'tools.rentFarm': 'इतर शेतकऱ्यांकडून शेतीची साधने आणि जमीन भाड्याने घ्या',
        'tools.farmTools': 'शेतीची साधने',
        'tools.farmland': 'शेतीची जमीन',
        'tools.myBookings': 'माझी बुकिंग',
        'tools.listYour': 'तुमचे साधन/जमीन सूचीबद्ध करा',
        'tools.searchTools': 'साधने किंवा स्थान शोधा...',
        'tools.category': 'श्रेणी',
        'tools.allTools': 'सर्व साधने',
        'tools.tractors': 'ट्रॅक्टर',
        'tools.tillers': 'टिलर',
        'tools.sprayers': 'स्प्रेअर',
        'tools.harvesters': 'हार्वेस्टर',
        'tools.other': 'इतर',
        'tools.new': 'नवीन',
        'tools.excellent': 'उत्कृष्ट',
        'tools.good': 'चांगले',
        'tools.fair': 'ठीक',
        'tools.dailyRate': 'दैनिक दर',
        'tools.security': 'सुरक्षा',
        'tools.bookNow': 'आता बुक करा',
        'tools.inquireNow': 'आता चौकशी करा',
        'tools.size': 'आकार',
        'tools.soilType': 'मातीचा प्रकार',
        'tools.monthlyRent': 'मासिक भाडे',
        'tools.waterSource': 'पाण्याचे स्त्रोत',
        'tools.total': 'एकूण',
        'tools.payNow': 'आता पैसे द्या',
        'tools.paid': 'दिले',
        'tools.noBookings': 'अद्याप कोणतेही बुकिंग नाही',
        'tools.startBooking': 'साधन किंवा जमीन बुक करून सुरुवात करा',
        'tools.startDate': 'प्रारंभ तारीख',
        'tools.endDate': 'अंतिम तारीख',
        'tools.confirmBooking': 'बुकिंग विनंतीची पुष्टी करा',
        'tools.sendInquiry': 'चौकशी आणि चॅट पाठवा',
        'tools.noteInquiry': 'टीप: "चौकशी पाठवा" वर क्लिक केल्यास चौकशी विनंती तयार होईल आणि जमिनीच्या मालकाशी चॅट उघडेल जेणेकरून तुम्ही तपशीलांवर चर्चा करू शकाल.',
        'tools.createListing': 'साधन सूची तयार करा',
        'tools.toolName': 'साधनाचे नाव',
        'tools.landTitle': 'जमिनीचे नाव',
        'schemes.allSchemes': 'सर्व योजना',
        'schemes.assistant': 'योजना सहायक',
        'schemes.search': 'योजना शोधा...',
        'schemes.state': 'राज्य',
        'schemes.category': 'श्रेणी',
        'schemes.viewDetails': 'तपशील पहा',
        'schemes.applyNow': 'आता अर्ज करा',
        'schemes.deadline': 'अंतिम तारीख',
        'schemes.central': 'केंद्रीय',
        'schemes.stateSmall': 'राज्य',
        'schemes.stateScheme': 'राज्य योजना',
        'schemes.centralScheme': 'केंद्रीय योजना',
        'schemes.noBookmarks': 'कोणतीही बुकमार्क केलेली योजना नाही',
        'schemes.noApplications': 'अद्याप कोणतेही अर्ज नाहीत',
        'schemes.eligibility': 'पात्रता निकष',
        'schemes.benefits': 'फायदे',
        'schemes.documents': 'आवश्यक कागदपत्रे',
        'schemes.process': 'अर्ज प्रक्रिया',
        'schemes.assistantTitle': 'योजना सहायक',
        'schemes.askAssistant': 'योजनांबद्दल विचारा...',
        'hero.feature.farmHealth': 'AI-आधारित शेत आरोग्य',
        'hero.feature.farmHealthDesc': 'रोग ओळखा, मातीचे विश्लेषण करा आणि स्मार्ट शिफारसी मिळवा',
        'hero.feature.market': 'बाजार इंटेलिजेंस',
        'hero.feature.marketDesc': 'रिअल-टाइम पिकांच्या किमती आणि मागणीचा अंदाज',
        'hero.feature.tools': 'साधने आणि जमीन कर्ज',
        'hero.feature.toolsDesc': 'जवळपासच्या शेतकऱ्यांकडून शेतीची अवजारे आणि जमीन भाड्याने घ्या',
        'hero.feature.marketplace': 'थेट बाजारपेठ',
        'hero.feature.marketplaceDesc': 'बिना बिचौलियांशिवाय पिके थेट खरेदीदारांना विका',
        'hero.feature.community': 'शेतकरी समुदाय',
        'hero.feature.communityDesc': 'शेतकऱ्यांशी जोडा, ज्ञान सामायिक करा आणि चॅट करा',
        'hero.feature.schemes': 'शासकीय योजना',
        'hero.feature.schemesDesc': 'सवलती आणि योजनांची माहिती सहज मिळवा',
        'hero.stats.farmers': 'नोंदणीकृत शेतकरी',
        'hero.stats.sales': 'पीक विक्री',
        'hero.stats.tools': 'सूचीबद्ध साधने',
        'hero.stats.states': 'कव्हर केलेली राज्ये',
        'market.directMarketplace': 'थेट पीक बाजारपेठ',
        'market.buySellSubtitle': 'पिके थेट खरेदी करा आणि विका - मध्यस्थ नाही, चांगल्या किमती',
        'market.trending': 'प्रचलित पिके',
        'market.browseCrops': 'पिके पहा',
        'market.myListings': 'माझी लिस्टिंग',
        'market.sellYourCrop': 'तुमचे पीक विका',
        'market.searchPlaceholder': 'पिके किंवा स्थान शोधा...',
        'market.organicOnly': 'केवळ सेंद्रिय',
        'market.per': 'प्रति',
        'market.available': 'उपलब्ध',
        'market.addCart': 'कार्टमध्ये जोडा',
        'market.chat': 'चॅट करा',
        'market.minOrder': 'किमान ऑर्डर',
        'market.organic': 'सेंद्रिय',
        'market.quality': 'गुणवत्ता',
        'market.searchCrops': 'पिके शोधा...',
        'market.filterBy': 'द्वारे फिल्टर',
        'market.allCrops': 'सर्व पिके',
        'market.highDemand': 'उच्च मागणी',
        'market.priceRising': 'किमती वाढत आहेत',
        'market.priceFalling': 'किमती कमी होत आहेत',
        'market.vsLastMonth': 'मागील महिन्याच्या तुलनेत',
        'market.demand': 'मागणी',
        'market.supply': 'पुरवठा',
        'market.priceHistory': 'किमतीचा इतिहास',
        'market.priceComparison': 'किमतीची तुलना',
        'market.marketDistribution': 'बाजार वितरण',
        'market.aiAnalysisDesc': 'आमचे AI ऐतिहासिक डेटा, हवामान पद्धती आणि भविष्यातील किमतींचा उच्च अचूकतेसह अंदाज लावण्यासाठी बाजारातील कल यांचे विश्लेषण करते.',
        'market.current': 'सध्याचे',
        'market.predicted': 'अपेक्षित',
        'market.confidence': 'विश्वासार्हता',
        'market.expectedToRise': 'वाढण्याची अपेक्षा आहे',
        'market.expectedToFall': 'कमी होण्याची अपेक्षा आहे',
        'market.aiRecommendation': 'AI शिफारस',
        'market.aiRecommendationDesc': 'सध्याच्या बाजारातील कल आणि अंदाजांवर आधारित, आम्ही खरेदी आणि विक्रीसाठी स्मार्ट शिफारसी प्रदान करतो।',
        'market.impact': 'प्रभाव',
        'market.categoryLabel': 'श्रेणी',
        'market.addListingTitle': 'तुमची फसल विका',
        'market.cropNameLabel': 'पिकाचे नाव',
        'market.varietyLabel': 'वाण',
        'market.pricePerUnitLabel': 'प्रति युनिट किंमत (₹)',
        'market.totalQuantityLabel': 'एकूण प्रमाण',
        'market.minOrderQuantityLabel': 'किमान ऑर्डर प्रमाण',
        'market.locationLabel': 'स्थान',
        'market.organicCheckbox': 'हे सेंद्रिय उत्पादन आहे',
        'market.descriptionLabel': 'वर्णन',
        'market.createListingBtn': 'लिस्टिंग तयार करा',
        'market.contactSeller': 'विक्रेत्याशी संपर्क साधा',
        'market.reviews': 'पुनरावलोकने',
        'footer.motto': 'स्वस्त भविष्यासाठी तंत्रज्ञान, बाजार प्रवेश आणि सामुदायिक समर्थनासह शेतकऱ्यांना सक्षम करणे।',
        'footer.quickLinks': 'त्वरित दुवे',
        'footer.support': 'सपोर्ट',
        'footer.stayUpdated': 'अपडेट रहा',
        'footer.newsletterDesc': 'योजना, बाजारभाव आणि शेतीविषयक टिपांवरील नवीनतम अपडेट्ससाठी आमच्या न्यूजलेटरची सदस्यता घ्या।',
        'footer.newsletterPlaceholder': 'तुमचा ईमेल प्रविष्ट करा',
        'footer.helpline': 'हेल्पलाईन',
        'footer.rights': 'सर्व हक्क राखीव.',
        'footer.madeWith': 'बनावट',
        'footer.forFarmers': 'भारतीय शेतकऱ्यांसाठी',
        'dashboard.yourLocation': 'तुमचे स्थान',
        'dashboard.alert': 'सतर्कता',
        'dashboard.perQuintal': '/क्विंटल'
    },
    gu: {
        'nav.farmHealth': 'ખેત સ્વાસ્થ્ય',
        'nav.market': 'બજાર',
        'nav.tools': 'સાધનો',
        'nav.chat': 'ચેટ',
        'nav.schemes': 'યોજનાઓ',
        'nav.dashboard': 'ડેશબોર્ડ',
        'nav.login': 'લોગિન',
        'nav.register': 'રજીસ્ટર',
        'hero.title': 'વધુ સારા આવતીકાલ માટે સ્માર્ટ ખેતી',
        'hero.subtitle': 'AgroConnect ખેડૂતોને AI-આધારિત આંતરદૃષ્ટિ, સીધી બજાર પહોંચ અને સહાયક સમુદાય સાથે સશક્ત બનાવે છે.',
        'hero.getStarted': 'શરૂ કરો',
        'hero.madeInIndia': 'ભારતમાં નિર્મિત',
        'hero.aiPlatform': 'AI-સંચાલિત પ્લેટફોર્મ',
        'dashboard.title': 'મારું ડેશબોર્ડ',
        'dashboard.subtitle': 'તમારા ખેતર, બજાર પ્રવૃત્તિ અને સૂચનાઓની ઝાંખી',
        'dashboard.farmHealth': 'ખેત સ્વાસ્થ્ય',
        'dashboard.activeListings': 'સક્રિય લિસ્ટિંગ',
        'dashboard.toolsListed': 'સૂચિબદ્ધ સાધનો',
        'dashboard.notifications': 'સૂચનાઓ',
        'market.intelligence': 'બજાર ઇન્ટેલિજન્સ',
        'market.buySell': 'ખરીદો અને વેચો',
        'market.title': 'AgroConnect બજાર',
        'market.intelHeader': 'પાક બજાર ઇન્ટેલિજન્સ',
        'market.intelSubtitle': 'રીઅલ-ટાઇમ પ્રાઇસ ટ્રેકિંગ, ડિમાન્ડ એનાલિસિસ અને AI-સંચાલિત આગાહીઓ',
        'market.livePrices': 'લાઇવ કિંમતો',
        'market.trends': 'ટ્રેન્ડ્સ',
        'market.predictions': 'AI આગાહીઓ',
        'market.insights': 'આંતરદૃષ્ટિ',
        'dashboard.weather': 'હવામાન',
        'dashboard.temp': 'તાપમાન',
        'dashboard.humidity': 'ભેજ',
        'dashboard.wind': 'પવન',
        'dashboard.rainfall': 'વરસાદ',
        'dashboard.alerts': 'સક્રિય એલર્ટ્સ',
        'dashboard.noAlerts': 'કોઈ સક્રિય એલર્ટ નથી',
        'dashboard.sales': 'વેચાણ ઝાંખી',
        'dashboard.prices': 'વર્તમાન બજાર ભાવ',
        'dashboard.recentNav': 'તાજેતરની સૂચનાઓ',
        'dashboard.pending': 'બાકી બુકિંગ',
        'dashboard.noPending': 'કોઈ બાકી બુકિંગ નથી',
        'dashboard.quick': 'ઝડપી પગલાં',
        'dashboard.checkCrops': 'પાક તપાસો',
        'dashboard.newListing': 'નવી લિસ્ટિંગ',
        'dashboard.listTool': 'સાધન ઉમેરો',
        'dashboard.messages': 'સંદેશાઓ',
        'dashboard.cropStatus': 'પાક આરોગ્ય સ્થિતિ',
        'dashboard.sustainable': 'ટકાઉ કૃષિ',
        'dashboard.joinMovement': 'AgroConnect સાથે હરિયાળી, સ્માર્ટ ભવિષ્ય તરફના આંદોલનમાં જોડાઓ.',
        'farm.title': 'ખેતર આરોગ્ય અને દેખરેખ',
        'farm.subtitle': 'AI-સંચાલિત પાક વિશ્લેષણ અને ક્ષેત્ર દેખરેખ',
        'schemes.title': 'સરકારી યોજનાઓ',
        'schemes.subtitle': 'કૃષિ સબસિડી અને લાભો શોધો અને અરજી કરો',
        'tools.title': 'સાધનો અને મશીનરી ઉધાર',
        'tools.subtitle': 'તમારા સમુદાયમાં કૃષિ મશીનરી ભાડે લો અથવા આપો',
        'chat.title': 'ખેડૂત સમુદાય',
        'chat.subtitle': 'જોડાઓ, શેર કરો અને સાથે વધો',
        'farm.healthMonitoring': 'ખેતર આરોગ્ય દેખરેખ',
        'farm.overview': 'ઝાંખી',
        'farm.aiAnalysis': 'AI વિશ્લેષણ',
        'farm.weather': 'હવામાન',
        'farm.soilData': 'જમીનનો ડેટા',
        'farm.lastChecked': 'છેલ્લી તપાસ',
        'farm.issues': 'સમસ્યાઓ',
        'farm.recommendations': 'ભલામણો',
        'farm.aiActions': 'AI-સંચાલિત કાર્યો',
        'farm.analyzeCrop': 'પાકની છબીનું વિશ્લેષણ કરો',
        'farm.checkWeather': 'હવામાન તપાસો',
        'farm.soilAnalysis': 'જમીન વિશ્લેષણ',
        'farm.fertilizerGuide': 'ખાતર માર્ગદર્શિકા',
        'farm.uploadCrop': 'પાકની છબી અપલોડ કરો',
        'farm.diseasesDetection': 'AI પાક રોગ તપાસ',
        'farm.plantDoctor': 'પ્લાન્ટ ડોક્ટર',
        'farm.analysisComplete': 'વિશ્લેષણ પૂર્ણ થયું',
        'farm.detectedIssue': 'શોધાયેલ સમસ્યા',
        'farm.affectedArea': 'પ્રભાવિત વિસ્તાર',
        'farm.confidence': 'આત્મવિશ્વાસ',
        'farm.severity': 'ગંભીરતા',
        'farm.soilComposition': 'જમીનની રચના',
        'farm.phLevel': 'pH સ્તર',
        'farm.nitrogen': 'નાઇટ્રોજન (N)',
        'farm.phosphorus': 'ફોસ્ફરસ (P)',
        'farm.potassium': 'પોટેશિયમ (K)',
        'farm.moisture': 'ભેજ',
        'farm.soilRecommendations': 'જમીનની ભલામણો',
        'farm.resolve': 'ઉકેલો',
        'farm.fireAlert': 'આગ એલર્ટ',
        'farm.theftAlert': 'ચોરી એલર્ટ',
        'farm.diseaseAlert': 'રોગ એલર્ટ',
        'farm.weatherAlert': 'હવામાન એલર્ટ',
        'farm.pestAlert': 'જીવાત એલર્ટ',
        'farm.goodHealth': 'સ્વસ્થ સ્થિતિ',
        'farm.badHealth': 'રોગગ્રસ્ત/જોખમમાં',
        'farm.detectedLabel': 'શોધાયેલ રોગ/સ્થિતિ',
        'farm.preventiveMeasures': 'નિવારક પગલાં',
        'farm.analyse': 'વિશ્લેષણ કરો',
        'farm.selectPlant': 'છોડનો પ્રકાર પસંદ કરો',
        'farm.choosePlant': 'છોડ પસંદ કરો...',
        'farm.uploadBtn': 'છબી અપલોડ કરો',
        'farm.cameraBtn': 'ફોટો લો',
        'farm.uploadInstruction': 'અસરગ્રસ્ત છોડના ભાગનો સ્પષ્ટ ફોટો લો અને અમારું AI રોગો, જીવાતો અને પોષક તત્વોની ઉણપ શોધી કાઢશે।',
        'farm.clickUpload': 'અપલોડ કરવા માટે ક્લિક કરો અથવા ડ્રેગ અને ડ્રોપ કરો',
        'farm.uploadLimit': '10MB સુધી JPG, PNG ને સપોર્ટ કરે છે',
        'farm.analyzing': 'વિશ્લેષણ થઈ રહ્યું છે...',
        'farm.analyzeAI': 'AI સાથે વિશ્લેષણ કરો',
        'farm.analyseAnother': 'બીજું વિશ્લેષણ કરો',
        'tools.toolsLand': 'સાધનો અને જમીન ધિરાણ',
        'tools.rentFarm': 'સાથી ખેડૂતો પાસેથી ખેતીના સાધનો અને જમીન ભાડે લો',
        'tools.farmTools': 'ખેતીના સાધનો',
        'tools.farmland': 'ખેતીની જમીન',
        'tools.myBookings': 'મારી બુકિંગ',
        'tools.listYour': 'તમારું સાધન/જમીન સૂચિબદ્ધ કરો',
        'tools.searchTools': 'સાધનો અથવા સ્થાન શોધો...',
        'tools.category': 'શ્રેણી',
        'tools.allTools': 'બધા સાધનો',
        'tools.tractors': 'ટ્રેક્ટર',
        'tools.tillers': 'ટીલર',
        'tools.sprayers': 'સ્પ્રેયર',
        'tools.harvesters': 'હાર્વેસ્ટર',
        'tools.other': 'અન્ય',
        'tools.new': 'નવું',
        'tools.excellent': 'ઉત્તમ',
        'tools.good': 'સારું',
        'tools.fair': 'ઠીક',
        'tools.dailyRate': 'દૈનિક દર',
        'tools.security': 'સુરક્ષા',
        'tools.bookNow': 'હમણાં બુક કરો',
        'tools.inquireNow': 'હમણાં પૂછપરછ કરો',
        'tools.size': 'કદ',
        'tools.soilType': 'જમીનનો પ્રકાર',
        'tools.monthlyRent': 'માસિક ભાડું',
        'tools.waterSource': 'પાણીનો સ્ત્રોત',
        'tools.total': 'કુલ',
        'tools.payNow': 'હમણાં ચૂકવો',
        'tools.paid': 'ચૂકવેલ',
        'tools.noBookings': 'હજી કોઈ બુકિંગ નથી',
        'tools.startBooking': 'સાધન અથવા જમીન બુક કરીને પ્રારંભ કરો',
        'tools.startDate': 'શરૂઆતની તારીખ',
        'tools.endDate': 'અંતિમ તારીખ',
        'tools.confirmBooking': 'બુકિંગ વિનંતીની પુષ્ટિ કરો',
        'tools.sendInquiry': 'પૂછપરછ અને ચેટ મોકલો',
        'tools.noteInquiry': 'નોંધ: "પૂછપરછ મોકલો" પર ક્લિક કરવાથી પૂછપરછ વિનંતી બનાવવામાં આવશે અને જમીન માલિક સાથે ચેટ ખુલશે જેથી તમે વિગતોની ચર્ચા કરી શકો.',
        'tools.createListing': 'સાધન લિસ્ટિંગ બનાવો',
        'tools.toolName': 'સાધનનું નામ',
        'tools.landTitle': 'જમીનનું શીર્ષક',
        'schemes.allSchemes': 'બધી યોજનાઓ',
        'schemes.assistant': 'યોજના મદદનીશ',
        'schemes.search': 'યોજનાઓ શોધો...',
        'schemes.state': 'રાજ્ય',
        'schemes.category': 'શ્રેણી',
        'schemes.viewDetails': 'વિગતો જુઓ',
        'schemes.applyNow': 'હમણાં અરજી કરો',
        'schemes.deadline': 'અંતિમ તારીખ',
        'schemes.central': 'કેન્દ્રીય',
        'schemes.stateSmall': 'રાજ્ય',
        'schemes.stateScheme': 'રાજ્ય યોજના',
        'schemes.centralScheme': 'કેન્દ્રીય યોજના',
        'schemes.noBookmarks': 'કોઈ બુકમાર્ક કરેલી યોજનાઓ નથી',
        'schemes.noApplications': 'હજી સુધી કોઈ અરજી નથી',
        'schemes.eligibility': 'પાત્રતા માપદંડ',
        'schemes.benefits': 'લાભો',
        'schemes.documents': 'જરૂરી દસ્તાવેજો',
        'schemes.process': 'અરજી પ્રક્રિયા',
        'schemes.assistantTitle': 'યોજના મદદનીશ',
        'schemes.askAssistant': 'યોજનાઓ વિશે પૂછો...',
        'hero.feature.farmHealth': 'AI-સંચાલિત ખેત સ્વાસ્થ્ય',
        'hero.feature.farmHealthDesc': 'રોગો શોધો, માટીનું વિશ્લેષણ કરો અને સ્માર્ટ ભલામણો મેળવો',
        'hero.feature.market': 'માર્કેટ ઇન્ટેલિજન્સ',
        'hero.feature.marketDesc': 'રીઅલ-ટાઇમ પાકના ભાવો અને માંગની આગાહી',
        'hero.feature.tools': 'સાધનો અને જમીન ધિરાણ',
        'hero.feature.toolsDesc': 'નજીકના ખેડૂતો પાસેથી ખેતીના સાધનો અને જમીન ભાડે લો',
        'hero.feature.marketplace': 'સીધું માર્કેટપ્લેસ',
        'hero.feature.marketplaceDesc': 'વચેટિયાઓ વગર પાક સીધો ખરીદદારોને વેચો',
        'hero.feature.community': 'ખેડૂત સમુદાય',
        'hero.feature.communityDesc': 'ખેડૂતો સાથે જોડાઓ, જ્ઞાન વહેંચો અને ચેટ કરો',
        'hero.feature.schemes': 'સરકારી યોજનાઓ',
        'hero.feature.schemesDesc': 'સબસિડી અને યોજનાઓની માહિતી સરળતાથી મેળવો',
        'hero.stats.farmers': 'નોંધાયેલા ખેડૂતો',
        'hero.stats.sales': 'પાકનું વેચાણ',
        'hero.stats.tools': 'લિસ્ટ કરેલા સાધનો',
        'hero.stats.states': 'કવર કરેલા રાજ્યો',
        'market.directMarketplace': 'સીધું પાક માર્કેટપ્લેસ',
        'market.buySellSubtitle': 'પાક સીધો ખરીદો અને વેચો - કોઈ વચેટિયા નહીં, સારા ભાવ',
        'market.trending': 'ટ્રેન્ડિંગ પાક',
        'market.browseCrops': 'પાક શોધો',
        'market.myListings': 'મારી લિસ્ટિંગ',
        'market.sellYourCrop': 'તમારો પાક વેચો',
        'market.searchPlaceholder': 'પાક કે સ્થાન શોધો...',
        'market.organicOnly': 'ફક્ત ઓર્ગેનિક',
        'market.per': 'દીઠ',
        'market.available': 'ઉપલબ્ધ',
        'market.addCart': 'કાર્ટમાં ઉમેરો',
        'market.chat': 'ચેટ કરો',
        'market.minOrder': 'ન્યૂનતમ ઓર્ડર',
        'market.organic': 'ઓર્ગેનિક',
        'market.quality': 'ગુણવત્તા',
        'market.searchCrops': 'પાક શોધો...',
        'market.filterBy': 'દ્વારા ફિલ્ટર',
        'market.allCrops': 'તમામ પાક',
        'market.highDemand': 'ઉચ્ચ માંગ',
        'market.priceRising': 'કિંમતો વધી રહી છે',
        'market.priceFalling': 'કિંમતો ઘટી રહી છે',
        'market.vsLastMonth': 'છેલ્લા મહિનાની તુલનામાં',
        'market.demand': 'માંગ',
        'market.supply': 'પુરવઠો',
        'market.priceHistory': 'કિંમત ઇતિહાસ',
        'market.priceComparison': 'કિંમત સરખામણી',
        'market.marketDistribution': 'બજાર વિતરણ',
        'market.aiAnalysisDesc': 'અમારું AI ઐતિહાસિક ડેટા, હવામાનની પેટર્ન અને બજારના વલણોનું વિશ્લેષણ કરીને ઉચ્ચ ચોકસાઈ સાથે ભવિષ્યની કિંમતોની આગાહી કરે છે.',
        'market.current': 'વર્તમાન',
        'market.predicted': 'અનુમાનિત',
        'market.confidence': 'આત્મવિશ્વાસ',
        'market.expectedToRise': 'વધવાની અપેક્ષા છે',
        'market.expectedToFall': 'ઘટવાની અપેક્ષા છે',
        'market.aiRecommendation': 'AI ભલામણ',
        'market.aiRecommendationDesc': 'વર્તમાન બજારના વલણો અને આગાહીઓના આધારે, અમે ખરીદવા અને વેચવા માટે સ્માર્ટ ભલામણો પ્રદાન કરીએ છીએ.',
        'market.impact': 'અસર',
        'market.categoryLabel': 'શ્રેણી',
        'market.addListingTitle': 'તમારો પાક વેચો',
        'market.cropNameLabel': 'પાકનું નામ',
        'market.varietyLabel': 'જાત',
        'market.pricePerUnitLabel': 'દીઠ એકમ કિંમત (₹)',
        'market.totalQuantityLabel': 'કુલ જથ્થો',
        'market.minOrderQuantityLabel': 'ન્યૂનતમ ઓર્ડર જથ્થો',
        'market.locationLabel': 'સ્થાન',
        'market.organicCheckbox': 'આ ઓર્ગેનિક ઉત્પાદન છે',
        'market.descriptionLabel': 'વર્ણન',
        'market.createListingBtn': 'લિસ્ટિંગ બનાવો',
        'market.contactSeller': 'વિક્રેતાનો સંપર્ક કરો',
        'market.reviews': 'સમીક્ષાઓ',
        'market.wishlistEmpty': 'તમારી વિશલિસ્ટ ખાલી છે',
        'market.saveCropsInterest': "તમને રસ હોય તેવા પાકને સાચવો",
        'market.uploadCropImage': 'પાકની છબી અપલોડ કરવા માટે ક્લિક કરો',
        'market.cropNamePlaceholder': 'પાકનું નામ',
        'market.varietyPlaceholder': 'જાત',
        'market.categoryPlaceholder': 'શ્રેણી',
        'market.pricePerUnitPlaceholder': 'દીઠ એકમ કિંમત (₹)',
        'market.unitPlaceholder': 'એકમ',
        'market.perKg': 'કિલો દીઠ',
        'market.perQuintal': 'ક્વિન્ટલ દીઠ',
        'market.perTon': 'ટન દીઠ',
        'market.totalQuantityPlaceholder': 'કુલ જથ્થો',
        'market.minOrderQuantityPlaceholder': 'ન્યૂનતમ ઓર્ડર જથ્થો',
        'market.locationPlaceholder': 'સ્થાન',
        'market.organicProduceLabel': 'આ ઓર્ગેનિક ઉત્પાદન છે',
        'market.descriptionPlaceholder': 'વર્ણન',
        'market.contactFarmer': 'વિક્રેતાનો સંપર્ક કરો',
        'market.startChat': 'ચેટ શરૂ કરો',
        'market.callFarmer': 'ખેડૂતને કોલ કરો',
        'market.addToCart': 'કાર્ટમાં ઉમેરો',
        'market.totalPrice': 'કુલ કિંમત',
        'market.cancel': 'રદ કરો',
        'market.confirmAdd': 'ઉમેરવાની પુષ્ટિ કરો',
        'market.quantity': 'જથ્થો',
        'footer.motto': 'ટકાઉ ભવિષ્ય માટે ટેકનોલોજી, બજાર પહોંચ અને સામુદાયિક સમર્થન સાથે ખેડૂતોને સશક્ત બનાવવું.',
        'footer.quickLinks': 'ઝડપી લિંક્સ',
        'footer.support': 'સપોર્ટ',
        'footer.stayUpdated': 'અપડેટ રહો',
        'footer.newsletterDesc': 'યોજનાઓ, બજારના ભાવો અને ખેતીની ટીપ્સ પર નવીનતમ અપડેટ્સ માટે અમારા ન્યૂઝલેટર પર સબ્સ્ક્રાઇબ કરો.',
        'footer.newsletterPlaceholder': 'તમારું ઇમેઇલ દાખલ કરો',
        'footer.helpline': 'હેલ્પલાઇન',
        'footer.rights': 'સર્વાધિકાર સુરક્ષિત.',
        'footer.madeWith': 'સાથે બનાવેલ',
        'footer.forFarmers': 'ભારતીય ખેડૂતો માટે',
        'dashboard.yourLocation': 'તમારું સ્થાન',
        'dashboard.alert': 'ચેતવણી',
        'dashboard.perQuintal': '/ક્વિન્ટલ'
    },
    bn: {
        'nav.farmHealth': 'খামার স্বাস্থ্য',
        'nav.market': 'বাজার',
        'nav.tools': 'সরঞ্জাম',
        'nav.chat': 'চ্যাট',
        'nav.schemes': 'প্রকল্প',
        'nav.dashboard': 'ড্যাশবোর্ড',
        'nav.login': 'লগইন',
        'nav.register': 'রেজিস্টার',
        'hero.title': 'উন্নত ভবিষ্যতের জন্য স্মার্ট চাষাবাদ',
        'hero.subtitle': 'AgroConnect কৃষকদের AI-চালিত অন্তর্দৃষ্টি, সরাসরি বাজারে প্রবেশ এবং একটি সহায়ক সম্প্রদায়ের সাথে ক্ষমতায়ন করে।',
        'hero.getStarted': 'শুরু করুন',
        'hero.madeInIndia': 'ভারতে তৈরি',
        'hero.aiPlatform': 'AI-চালিত প্ল্যাটফর্ম',
        'dashboard.title': 'আমার ড্যাশবোর্ড',
        'dashboard.subtitle': 'আপনার খামার, বাজার কার্যক্রম এবং বিজ্ঞপ্তির সংক্ষিপ্ত রূপ',
        'dashboard.farmHealth': 'খামার স্বাস্থ্য',
        'dashboard.activeListings': 'সক্রিয় তালিকা',
        'dashboard.toolsListed': 'তালিকাভুক্ত সরঞ্জাম',
        'dashboard.notifications': 'বিজ্ঞপ্তি',
        'market.intelligence': 'বাজার বুদ্ধিমত্তা',
        'market.buySell': 'কেনা ও বেচা',
        'market.title': 'AgroConnect বাজার',
        'market.intelHeader': 'ফসল বাজার বুদ্ধিমত্তা',
        'market.intelSubtitle': 'রিয়েল-টাইম মূল্য ট্র্যাকিং, চাহিদা বিশ্লেষণ এবং AI-চালিত পূর্বাভাস',
        'market.livePrices': 'লাইভ দাম',
        'market.trends': 'প্রবণতা',
        'market.predictions': 'AI পূর্বাভাস',
        'market.insights': 'অন্তর্দৃষ্টি',
        'dashboard.weather': 'আবহাওয়া',
        'dashboard.temp': 'তাপমাত্রা',
        'dashboard.humidity': 'আর্দ্রতা',
        'dashboard.wind': 'বাতাস',
        'dashboard.rainfall': 'বৃষ্টিপাত',
        'dashboard.alerts': 'সক্রিয় সতর্কতা',
        'dashboard.noAlerts': 'কোন সক্রিয় সতর্কতা নেই',
        'dashboard.sales': 'বিক্রয় সারাংশ',
        'dashboard.prices': 'বর্তমান বাজার দর',
        'dashboard.recentNav': 'সাম্প্রতিক বিজ্ঞপ্তি',
        'dashboard.pending': 'বাকি বুকিং',
        'dashboard.noPending': 'কোন বাকি বুকিং নেই',
        'dashboard.quick': 'দ্রুত পদক্ষেপ',
        'dashboard.checkCrops': 'ফসল পরীক্ষা করুন',
        'dashboard.newListing': 'নতুন তালিকা',
        'dashboard.listTool': 'সরঞ্জাম যোগ করুন',
        'dashboard.messages': 'বার্তা',
        'dashboard.cropStatus': 'ফসলের স্বাস্থ্য অবস্থা',
        'dashboard.sustainable': 'টেকসই কৃষি',
        'dashboard.joinMovement': 'AgroConnect-এর সাথে একটি সবুজ এবং স্মার্ট ভবিষ্যতের আন্দোলনে যোগ দিন।',
        'farm.title': 'খামার স্বাস্থ্য ও পর্যবেক্ষণ',
        'farm.subtitle': 'AI-চালিত ফসল বিশ্লেষণ এবং খামার পর্যবেক্ষণ',
        'schemes.title': 'সরকারি প্রকল্প',
        'schemes.subtitle': 'কৃষি ভরতুকি এবং সুবিধাগুলি খুঁজুন এবং আবেদন করুন',
        'tools.title': 'সরঞ্জাম এবং যন্ত্রপাতি ধার',
        'tools.subtitle': 'আপনার সম্প্রদায়ের মধ্যে খামারের যন্ত্রপাতি ভাড়া নিন বা দিন',
        'chat.title': 'কৃষক সম্প্রদায়',
        'chat.subtitle': 'যুক্ত হন, ভাগ করুন এবং একসাথে বাড়ুন',
        'farm.healthMonitoring': 'খামার স্বাস্থ্য পর্যবেক্ষণ',
        'farm.overview': 'সারসংক্ষেপ',
        'farm.aiAnalysis': 'AI বিশ্লেষণ',
        'farm.weather': 'আবহাওয়া',
        'farm.soilData': 'মাটির তথ্য',
        'farm.lastChecked': 'শেষ পরীক্ষা',
        'farm.issues': 'সমস্যা',
        'farm.recommendations': 'সুপারিশ',
        'farm.aiActions': 'AI-চালিত পদক্ষেপ',
        'farm.analyzeCrop': 'ফসলের ছবি বিশ্লেষণ করুন',
        'farm.checkWeather': 'আবহাওয়া পরীক্ষা করুন',
        'farm.soilAnalysis': 'মাটি বিশ্লেষণ',
        'farm.fertilizerGuide': 'সার গাইড',
        'farm.uploadCrop': 'ফসলের ছবি আপলোড করুন',
        'farm.diseasesDetection': 'AI ফসল রোগ শনাক্তকরণ',
        'farm.plantDoctor': 'প্ল্যান্ট ডাক্তার',
        'farm.analysisComplete': 'বিশ্লেষণ সম্পন্ন',
        'farm.detectedIssue': 'শনাক্তকৃত সমস্যা',
        'farm.affectedArea': 'আক্রান্ত এলাকা',
        'farm.confidence': 'নির্ভরযোগ্যতা',
        'farm.severity': 'তীব্রতা',
        'farm.soilComposition': 'মাটির গঠন',
        'farm.phLevel': 'pH স্তর',
        'farm.nitrogen': 'নাইট্রোজেন (N)',
        'farm.phosphorus': 'ফসফরাস (P)',
        'farm.potassium': 'পটাশিয়াম (K)',
        'farm.moisture': 'আর্দ্রতা',
        'farm.soilRecommendations': 'মাটি সংক্রান্ত সুপারিশ',
        'farm.resolve': 'সমাধান করুন',
        'farm.fireAlert': 'অগ্নি সতর্কতা',
        'farm.theftAlert': 'চুরি সতর্কতা',
        'farm.diseaseAlert': 'রোগ সতর্কতা',
        'farm.weatherAlert': 'আবহাওয়া সতর্কতা',
        'farm.pestAlert': 'কীটপতঙ্গ সতর্কতা',
        'farm.goodHealth': 'সুস্থ অবস্থা',
        'farm.badHealth': 'রোগাক্রান্ত/ঝুঁকিপূর্ণ',
        'farm.detectedLabel': 'সনাক্ত করা রোগ/অবস্থা',
        'farm.preventiveMeasures': 'প্রতিরোধমূলক ব্যবস্থা',
        'farm.analyse': 'বিশ্লেষণ করুন',
        'farm.selectPlant': 'গাছের ধরণ নির্বাচন করুন',
        'farm.choosePlant': 'গাছ নির্বাচন করুন...',
        'farm.uploadBtn': 'ছবি আপলোড করুন',
        'farm.cameraBtn': 'ছবি তুলুন',
        'farm.uploadInstruction': 'আক্রান্ত উদ্ভিদের অংশের একটি পরিষ্কার ছবি তুলুন এবং আমাদের এআই রোগ, পোকামাকড় এবং পুষ্টির অভাব সনাক্ত করবে।',
        'farm.clickUpload': 'আপলোড করতে ক্লিক করুন বা টেনে আনুন',
        'farm.uploadLimit': '১০ মেগাবাইট পর্যন্ত JPG, PNG সমর্থন করে',
        'farm.analyzing': 'বিশ্লেষণ করা হচ্ছে...',
        'farm.analyzeAI': 'এআই দিয়ে বিশ্লেষণ করুন',
        'farm.analyseAnother': 'আরেকটি বিশ্লেষণ করুন',
        'tools.toolsLand': 'সরঞ্জাম এবং জমি ধার',
        'tools.rentFarm': 'সহকর্মী কৃষকদের কাছ থেকে খামারের সরঞ্জাম এবং জমি ভাড়া নিন',
        'tools.farmTools': 'খামারের সরঞ্জাম',
        'tools.farmland': 'ফসলি জমি',
        'tools.myBookings': 'আমার বুকিং',
        'tools.listYour': 'আপনার সরঞ্জাম/জমি তালিকাভুক্ত করুন',
        'tools.searchTools': 'সরঞ্জাম বা অবস্থান খুঁজুন...',
        'tools.category': 'বিভাগ',
        'tools.allTools': 'সব সরঞ্জাম',
        'tools.tractors': 'ট্রাক্টর',
        'tools.tillers': 'টিলার',
        'tools.sprayers': 'স্প্রেয়ার',
        'tools.harvesters': 'হারভেস্টার',
        'tools.other': 'অন্যান্য',
        'tools.new': 'নতুন',
        'tools.excellent': 'চমৎকার',
        'tools.good': 'ভালো',
        'tools.fair': 'মোটামুটি',
        'tools.dailyRate': 'দৈনিক ভাড়া',
        'tools.security': 'নিরাপত্তা আমানত',
        'tools.bookNow': 'এখনই বুক করুন',
        'tools.inquireNow': 'এখনই অনুসন্ধান করুন',
        'tools.size': 'আকার',
        'tools.soilType': 'মাটির ধরন',
        'tools.monthlyRent': 'মাসিক ভাড়া',
        'tools.waterSource': 'জলের উৎস',
        'tools.total': 'মোট',
        'tools.payNow': 'এখনই পেমেন্ট করুন',
        'tools.paid': 'পেমেন্ট করা হয়েছে',
        'tools.noBookings': 'এখনও কোন বুকিং নেই',
        'tools.startBooking': 'একটি সরঞ্জাম বা জমি বুক করে শুরু করুন',
        'tools.startDate': ' শুরুর তারিখ',
        'tools.endDate': 'শেষ তারিখ',
        'tools.confirmBooking': 'বুকিং অনুরোধ নিশ্চিত করুন',
        'tools.sendInquiry': 'অনুসন্ধান এবং চ্যাট পাঠান',
        'tools.noteInquiry': 'দ্রষ্টব্য: "অনুসন্ধান পাঠান" এ ক্লিক করলে একটি অনুসন্ধানের অনুরোধ তৈরি হবে এবং জমির মালিকের সাথে একটি চ্যাট খুলবে যাতে আপনি বিস্তারিত আলোচনা করতে পারেন।',
        'tools.createListing': 'সরঞ্জাম তালিকা তৈরি করুন',
        'tools.toolName': 'সরঞ্জামের নাম',
        'tools.landTitle': 'জমির শিরোনাম',
        'schemes.total': 'মোট প্রকল্প',
        'schemes.myApplications': 'আমার আবেদন',
        'schemes.bookmarked': 'বুকমার্ক করা',
        'schemes.farmersBenefited': 'উপকৃত কৃষক',
        'schemes.allSchemes': 'সব প্রকল্প',
        'schemes.assistant': 'প্রকল্প সহকারী',
        'schemes.search': 'প্রকল্প খুঁজুন...',
        'schemes.state': 'রাজ্য',
        'schemes.category': 'বিভাগ',
        'schemes.viewDetails': 'বিস্তারিত দেখুন',
        'schemes.applyNow': 'এখনই আবেদন করুন',
        'schemes.deadline': 'ডেডলাইন',
        'schemes.central': 'কেন্দ্রীয়',
        'schemes.stateSmall': 'রাজ্য',
        'schemes.stateScheme': 'রাজ্য প্রকল্প',
        'schemes.centralScheme': 'কেন্দ্রীয় প্রকল্প',
        'schemes.noBookmarks': 'কোন বুকমার্ক করা প্রকল্প নেই',
        'schemes.noApplications': 'এখনও কোন আবেদন নেই',
        'schemes.eligibility': 'যোগ্যতার মানদণ্ড',
        'schemes.benefits': 'সুবিধা',
        'schemes.documents': 'প্রয়োজনীয় নথি',
        'schemes.process': 'আবেদন প্রক্রিয়া',
        'schemes.assistantTitle': 'প্রকল্প সহকারী',
        'schemes.askAssistant': 'প্রকল্প সম্পর্কে জিজ্ঞাসা করুন...',
        'hero.feature.farmHealth': 'AI-চালিত খামার স্বাস্থ্য',
        'hero.feature.farmHealthDesc': 'রোগ শনাক্ত করুন, মাটি বিশ্লেষণ করুন এবং স্মার্ট পরামর্শ পান',
        'hero.feature.market': 'বাজার বুদ্ধিমত্তা',
        'hero.feature.marketDesc': 'রিয়েল-টাইম ফসলের দাম এবং চাহিদা পূর্বাভাস',
        'hero.feature.tools': 'সরঞ্জাম এবং জমি ধার',
        'hero.feature.toolsDesc': 'আশেপাশের কৃষকদের কাছ থেকে খামারের সরঞ্জাম এবং জমি ভাড়া নিন',
        'hero.feature.marketplace': 'সরাসরি বাজার',
        'hero.feature.marketplaceDesc': 'মধ্যস্বত্বভোগী ছাড়াই সরাসরি ক্রেতাদের কাছে ফসল বিক্রি করুন',
        'hero.feature.community': 'কৃষক সম্প্রদায়',
        'hero.feature.communityDesc': 'কৃষকদের সাথে সংযোগ করুন, জ্ঞান ভাগ করুন এবং চ্যাট করুন',
        'hero.feature.schemes': 'সরকারি প্রকল্প',
        'hero.feature.schemesDesc': 'সহজেই ভর্তুকি এবং প্রকল্পের তথ্য অ্যাক্সেস করুন',
        'hero.stats.farmers': 'নিবন্ধিত কৃষক',
        'hero.stats.sales': 'ফসল বিক্রয়',
        'hero.stats.tools': 'তালিকাভুক্ত সরঞ্জাম',
        'hero.stats.states': 'কভার করা রাজ্য',
        'market.directMarketplace': 'সরাসরি ফসলের বাজার',
        'market.buySellSubtitle': 'ফসলের সরাসরি কেনা-বেচা - মধ্যস্থতাকারী নেই, ভালো দাম',
        'market.trending': 'ট্রেন্ডিং ফসল',
        'market.browseCrops': 'ফসল ব্রাউজ করুন',
        'market.myListings': 'আমার লিস্টিং',
        'market.sellYourCrop': 'আপনার ফসল বিক্রি করুন',
        'market.searchPlaceholder': 'ফসল বা অবস্থান খুঁজুন...',
        'market.organicOnly': 'শুধুমাত্র জৈব',
        'market.per': 'প্রতি',
        'market.available': 'উপলব্ধ',
        'market.addCart': 'কার্টে যোগ করুন',
        'market.chat': 'চ্যাট করুন',
        'market.minOrder': 'নূন্যতম অর্ডার',
        'market.organic': 'জৈব',
        'market.quality': 'মান',
        'market.searchCrops': 'ফসল খুঁজুন...',
        'market.filterBy': 'ফিল্টার করুন',
        'market.allCrops': 'সব ফসল',
        'market.highDemand': 'উচ্চ চাহিদা',
        'market.priceRising': 'দাম বাড়ছে',
        'market.priceFalling': 'দাম কমছে',
        'market.vsLastMonth': 'গত মাসের তুলনায়',
        'market.demand': 'চাহিদা',
        'market.supply': 'সরবরাহ',
        'market.priceHistory': 'মূল্যের ইতিহাস',
        'market.priceComparison': 'মূল্যের তুলনা',
        'market.marketDistribution': 'বাজার বিতরণ',
        'market.aiAnalysisDesc': 'আমাদের AI ঐতিহাসিক তথ্য, আবহাওয়ার ধরণ এবং বাজারের প্রবণতা বিশ্লেষণ করে উচ্চ নির্ভুলতার সাথে ভবিষ্যতের দামের পূর্বাভাস দেয়।',
        'market.current': 'বর্তমান',
        'market.predicted': 'পূর্বাভাস',
        'market.confidence': 'নির্ভরযোগ্যতা',
        'market.expectedToRise': 'বাড়বে বলে আশা করা হচ্ছে',
        'market.expectedToFall': 'কমবে বলে আশা করা হচ্ছে',
        'market.aiRecommendation': 'AI সুপারিশ',
        'market.aiRecommendationDesc': 'বর্তমান বাজারের প্রবণতা এবং পূর্বাভাসের ভিত্তিতে, আমরা কেনা এবং বিক্রির জন্য স্মার্ট সুপারিশ প্রদান করি।',
        'market.impact': 'প্রভাব',
        'market.categoryLabel': 'বিভাগ',
        'market.addListingTitle': 'আপনার ফসল বিক্রি করুন',
        'market.cropNameLabel': 'ফসলের নাম',
        'market.varietyLabel': 'জাত',
        'market.pricePerUnitLabel': 'প্রতি ইউনিটের দাম (₹)',
        'market.totalQuantityLabel': 'মোট পরিমাণ',
        'market.minOrderQuantityLabel': 'নূন্যতম অর্ডারের পরিমাণ',
        'market.locationLabel': 'অবস্থান',
        'market.organicCheckbox': 'এটি একটি জৈব পণ্য',
        'market.descriptionLabel': 'বিবরণ',
        'market.createListingBtn': 'তালিকা তৈরি করুন',
        'market.contactSeller': 'বিক্রেতার সাথে যোগাযোগ করুন',
        'market.reviews': 'রিভিউ',
        'market.wishlistEmpty': 'আপনার উইশলিস্ট খালি',
        'market.saveCropsInterest': "আপনার আগ্রহের ফসলগুলি সংরক্ষণ করুন",
        'market.uploadCropImage': 'ফসলের ছবি আপলোড করতে ক্লিক করুন',
        'market.cropNamePlaceholder': 'ফসলের নাম',
        'market.varietyPlaceholder': 'জাত',
        'market.categoryPlaceholder': 'বিভাগ',
        'market.pricePerUnitPlaceholder': 'প্রতি ইউনিটের দাম (₹)',
        'market.unitPlaceholder': 'ইউনিট',
        'market.perKg': 'প্রতি কেজি',
        'market.perQuintal': 'প্রতি কুইন্টাল',
        'market.perTon': 'প্রতি টন',
        'market.totalQuantityPlaceholder': 'মোট পরিমাণ',
        'market.minOrderQuantityPlaceholder': 'ননূ্যতম অর্ডারের পরিমাণ',
        'market.locationPlaceholder': 'অবস্থান',
        'market.organicProduceLabel': 'এটি একটি জৈব পণ্য',
        'market.descriptionPlaceholder': 'বিবরণ',
        'market.contactFarmer': 'বিক্রেতার সাথে যোগাযোগ করুন',
        'market.startChat': 'চ্যাট শুরু করুন',
        'market.callFarmer': 'কৃষককে কল করুন',
        'market.addToCart': 'কার্টে যোগ করুন',
        'market.totalPrice': 'মোট দাম',
        'market.cancel': 'বাতিল করুন',
        'market.confirmAdd': 'যোগ নিশ্চিত করুন',
        'market.quantity': 'পরিমাণ',
        'footer.motto': 'একটি টেকসই ভবিষ্যতের জন্য প্রযুক্তি, বাজারে প্রবেশ এবং সম্প্রদায় সহায়তার মাধ্যমে কৃষকদের ক্ষমতায়ন করা।',
        'footer.quickLinks': 'সহজ লিঙ্ক',
        'footer.support': 'সাহায্য',
        'footer.stayUpdated': 'আপডেট থাকুন',
        'footer.newsletterDesc': 'প্রকল্প, বাজারের দাম এবং চাষের টিপস সম্পর্কে সর্বশেষ আপডেটের জন্য আমাদের নিউজলেটারে সাবস্ক্রাইব করুন।',
        'footer.newsletterPlaceholder': 'আপনার ইমেল প্রবেশ করুন',
        'footer.helpline': 'হেল্পলাইন',
        'footer.rights': 'সমস্ত অধিকার সংরক্ষিত।',
        'footer.madeWith': 'তৈরি',
        'footer.forFarmers': 'ভারতীয় কৃষকদের জন্য',
        'dashboard.yourLocation': 'আপনার অবস্থান',
        'dashboard.alert': 'সতর্কতা',
        'dashboard.perQuintal': '/কুইন্টাল'
    }
};

export const useLanguageStore = create<LanguageState>((set, get) => ({
    language: 'en',
    setLanguage: (lang) => set({ language: lang }),
    t: (key) => {
        const { language } = get();
        return translations[language][key] || key;
    }
}));
